### ISSUE TITLE
Beginner questions

### ISSUE THREAD

**Issue by mrctito** [UXDivers/Grial-UI-Kit-Support#119]
Dear sirs,

Don't you have any videos showing how to start a new project using Grial, adding new pages and customizing each one?

It seems that Grial is a great product, but it is very complicated (to me) to understand where do I need to write my own code. I am a good C# programmer, but I am newbie in Xamarin.

Unfortunately I still did not understand if I should inherit from Grial's object classes or not. 

And it is not clear to me how do I navigate between pages using Grial. Do I should to use any special class?

It should be wonderful if would be there some document showing side by side  the basic steps in Xamarin alone, and in Xamarin with Grial.

Another question: do you have the samples project without xaml, with all code wrote in C#, inside a page class? 

Do you have more samples? It would be wonderful if you had small samples, to show specific concepts in each one.

I would be very glad for any help,
Regards,
Marcos

**Comment by jpbrocca** [comment]
Hi @mrctito,

thanks for your feedback.
We are working hard on next version of the product to make things easier

Meanwhile, here are a few tips to help you:

1. Depending on what is your goal, the fastest way for you to start is to build on top of our sample, then everything would be much easier because you won't have to deal with lots of copy paste and and you will also need a lot of "find and replace" actions, change build actions, etc.
The alternative would be to start on a new project and copy everything but I don't recommend it, not at least until you get a little bit more familiar with Xamarin and Grial.

2. Basically Grial is built on top of Xamarin Forms (not Xamarin native) and our two main core things are:
 - artina dlls: This is where the CustomRenderes and shared logic relies for our controls
 - XAML: This is mostly the pages and templates you will be using.

We don't provide the XAML templates as C# because we believe that XAML is much more easy and maintainable for UI.

There are also the theme infrastructure (your app's look and feel and the required files to make that work on each platform), the helpers, models and view/models (the purpose for those is to provide a way for you to set up your data and "feed" your UI -pages and templates- with data).

There is also our navigation system which we provide on our sample. Look for the `NaviationsServices.cs` on the helpers folder.

Hope this help you!
Best regards,
JP

**Comment by mrctito** [comment]
I am missing comments in source code to explain the main concepts and make easier to customize. I would like to start updating the sample to work with an login's workflow, but the setup of app start first page is a little confused and there are no comments to guide us.

It would be very useful if you provide small samples for each page template.

Thank you.

**Comment by mrctito** [comment]
Guys,

You need to comment all source code and provide several samples, or warn the buyers about what are they buying.

And about your comment about XAML be easier to mantaining, I disagree with you if we are talking about a reusable library of compoents. You must develop pages not as templates to do copy and paste, but to be inherited, customizing it throught virtual methods or setting properties.

I am very disappointed with this product.

**Comment by jpbrocca** [comment]
HI @mrctito,
thanks for your feedback.

Grial is not a strictly a reusable library of components, is a set of templates covering the most typical mobile UI Patterns made for xamarin forms (in XAML).

If this is not the product you were looking for then I can give you a refund.
If that is the case, then please send an email to hello@uxdivers.com with your purchase details (your name, date, order number, etc.).

If is there anything else I could do to help please let me know.

Best,
JP
