### ISSUE TITLE
Button Pressed delay

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#120]
Hi GrialUI Support Team,

I am learning the structure of the GrialUI Sample. While testing the buttons on the "ThemePage", I realised that it does not response swiftly as compare to the buttons at SettingsPage. I need hold down the button for a flick of second to see the button in "pressed" stated while the buttons at SettingsPage is very responsive.

Why it is so? Any suggestion?

Thanks,
Dennis

**Comment by jpbrocca** [comment]
Hi @denfung,

On which platform are you testing ?
I guess what you are describing is the different buttons provided with the kit and how the behave.
So the ones on the ThemePage are the native ones meaning the default rendering for the buttons on the platform.

The rounded buttons (artina:Button) is a CustomRenderer we made specially for Android in order to allow to customize the rounded corners on Android (which is not possible under AppCompatV7 on xamarin forms out of the box).

The default buttons have their animation and visual states.

Hope that helps.

Best,
JP
