### ISSUE TITLE
/Droid/Resources/values/Style.xml(0,0): Error APT0000: No resource found that matches the given name (at 'android:color' with value '@color/AccentColor'). (APT0000)

### ISSUE THREAD

**Issue by K232** [UXDivers/Grial-UI-Kit-Support#141]
Hi all,

I've had several problems integrating Grial UI Kit into my (relatively new) Xamarin Forms (with Xamarin Studio) project because some steps in the integration description are just missing. Anyway, for iOS it's running fine now, but I still don't get the Droid version to work. Error message is:

> /Droid/Resources/values/Style.xml(0,0): Error APT0000: No resource found that matches the given name (at 'android:color' with value '@color/AccentColor'). (APT0000)

I've created new T4 Template files in both PCL and Droid/values and copied the data from the sample project. I've also updated line 16 (one of the things which was not explained) to resolve my correct path ("../../../MyApp/App.xaml"). I've changed the accent color in my app.xaml and ran T4 processing. It works fine in iOS, new color is used. But Droid does not compile due to this error.

I've found the same problem here at #27 but the solution is just to follow the guidelines which I already did.

**Comment by jpbrocca** [comment]
Hi @K232 K232,

You will need to create the result of the T4 compilation manually in order to get everything working.
The error you get is complaining about not finding the AccentColor which is defined on your Android project inside the `Colors.xml ` file (which is not being generated because T4 is failing on latest versions of Xamarin and Visual Studio).

Basically, add a new `Colors.xml` file on this folder:
![image](https://cloud.githubusercontent.com/assets/15996999/22940936/58f8b060-f2c2-11e6-891a-579a4437b402.png)

Then simply add this code (remember to change color values to match your App.xaml AccentColor value):
```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
	<!-- Artina Exported Colors -->
	<color name="AccentColor">#FFDA125F</color>
	<color name="InverseTextColor">#FFFFFFFF</color>
</resources>
```

Take a look at this link for more info:
https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Can't-compile-T4-templates

Let me know if you need more help.

Best,
JP

**Comment by K232** [comment]
Yes, that fixed it, thanks JP! Strange because I try to build my app close to your Grial app and so I already had the Colors.xml available. I've copied the content of existing XML, deleted the Colors.tt and created a new Colors.xml as advised, and now it's working fine also on Droid. Many thanks!

![droid resources values colors](https://cloud.githubusercontent.com/assets/685016/22945404/713c1932-f2f4-11e6-926b-9c9fa2fe6e7c.png)

P.S. You might want to update the GettingStarted.md included with the download as this still says that you have to use a Colors.tt in the Droid Resources...

**Comment by jpbrocca** [comment]
Hi @K232,
thanks for letting me know!

Best,
JP
