### ISSUE TITLE
Horizontal scrolling tab feature (Tab page)

### ISSUE THREAD

**Issue by ombinar** [UXDivers/Grial-UI-Kit-Support#149]
Hello,

Are the tabs only designed for 3 max right now? Do you have any guidance on how I can have more than 3 so I can scroll them back and forth?

Thanks,

Ricky

**Comment by jpbrocca** [comment]
Hi @ombinar,

No :)
...this is just the sample we provide showing how you can use the `TabbedPage`.
To achieve what you need simply add the following:

`app:tabMode="scrollable"`

To the `Tabs.axml` file located on this folder on your Android project:
![image](https://cloud.githubusercontent.com/assets/15996999/23885420/8f44740c-0851-11e7-93bb-3ef58f47dea0.png)

![image](https://cloud.githubusercontent.com/assets/15996999/23885373/5477066e-0851-11e7-9c6b-9c0454f32a92.png)

Keep in mind that the way the tabs will be displayed will be slightly different (they will look left aligned instead of center aligned as in our sample).

Please remember to close this issue after you confirm it works.

Regards and thanks,
JP

**Comment by ombinar** [comment]
Perfect! Exactly what I'm looking for. Thank you.

**Comment by jpbrocca** [comment]
You are welcome...remember to close issues if the proposed fix works ;)
