### ISSUE TITLE
Gorilla Player Issues

### ISSUE THREAD

**Issue by johncdoherty** [UXDivers/Grial-UI-Kit-Support#157]
I haven't been able to get Gorilla Player working with the Grial 2.0 starter project. I had it working with Grial 1.5.2 though. I've attempted w/ and w/o the Gorilla SDK as outlined here: [https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK](url)

This is the error I'm receiving:
![image](https://cloud.githubusercontent.com/assets/1096096/24168789/1d6c35a4-0e41-11e7-8ad5-f14da40c5000.png)
![image](https://cloud.githubusercontent.com/assets/1096096/24168817/2ba5effc-0e41-11e7-8f35-a420d334fcae.png)
![image](https://cloud.githubusercontent.com/assets/1096096/24168850/4c1bd986-0e41-11e7-94ef-61f655f8ff9a.png)

My Gorilla.json file currently looks like this:

```
{
	"knownAssemblies": [
		{
			"name": "UXDivers.Artina.Shared",
			"types": null
		},
        {
			"name": "UXDivers.Effects",
			"types": null
		},
        {
			"name": "UXDivers.Artina.Shared.Base",
			"types": null
		},
        {
			"name": "FFImageLoading.Transformations",
			"types": null
		},
        {
			"name": "FFImageLoading.Forms",
			"types": null
		}
	],

    "navigationPage": {
        "all": true
    }
}
```

Do you have any suggestions on how to get this working, I've been going in circles for a while now?
Thanks,
John

**Comment by LeoHere** [comment]
@johncdoherty the error you are seeing is because Gorilla 0.9.1.2 does not support ```MergedWith```, which is used by Grial in the ```App.Xaml```. You will need a newer version of Gorilla to preview Grial. Please, send a email to hello@grialkit.com asking for it and mentioning this issue.

**Comment by Jeremywhiteley** [comment]
I am having this same issue.   Also I can't preview my views in the Xamarin preview either.   When I go to update the Gorilla player, it says I am using the latest one.

**Comment by qaliwebguru** [comment]
There are some issues coming for me as well. 

1- Its crashing unexpectedly.
2- For every page, device showing message "Gorilla needed SDK" in Grial full - Gorilla ready project

Any fix to this?

Thanks

**Comment by LeoHere** [comment]
@qaliwebguru probably the reason is that you are using Gorilla Player app from the store to preview.  Grial, came preconfigured with Gorilla SDK. In order to preview it you will need to start Grial using Gorilla Configuration, which will start Gorilla instead of Grial. After that you should be able to preview Grial.

The video in this blog post [briefly shows you this](https://blog.uxdivers.com/2017/09/07/grial-ui-kit-gorilla-player-out-of-the-box/).

I'm closing this issue now since it is a bit old. If you still have issues please open a new ticket.
