### ISSUE TITLE
Image not loading : MultipleScrollMainItem

### ISSUE THREAD

**Issue by crakhi** [UXDivers/Grial-UI-Kit-Support#158]
Team,
I just downloaded the sample from admin console and when I am running the full sample, in the Grial Movies page the MainItem image is just showing up and disappears immediately, leaving it with a black background. Not sure if it is because of ffimageloading, I'm not pretty sure about it and I haven't make any changes. Anything I can change to correct it?

```
VS 2017
5" KitKat (4.4) Android 4.4-API19 Emulator
```

**Comment by jpbrocca** [comment]
Hi @crakhi,
I guess you are using Visual Studio emulator for Android, right?

In the past we had detected it has some issues with normal images (sometimes it displayed images wrong while on devices images were properly displayed).
Can you try with another emulator just to be sure?

Also, you could replace:

`<ffimageloading:CachedImage ... />`

...with a simple image and test:

`<Image ... />`

Not sure about your results because this is a remote image and FFImageLoading does an excellent job loading images compared to the Image provided with forms.

As a side note, this is how we set the properties for `ffimageloading:CachedImage`, you could change some of those properties -only for `DashboardMultipleScrollMainItemTemplate`- and check:

```
<!-- FFIMAGELOADING STYLES -->
<Style TargetType="ffimageloading:CachedImage">	
    <Setter Property="LoadingPlaceholder" Value="loading_placeholder.png" />
    <Setter Property="BitmapOptimizations" Value="true" />
    <Setter Property="DownsampleToViewSize" Value="true" />
    <Setter Property="TransparencyEnabled" Value="false" />
    <Setter Property="RetryCount" Value="3" />
    <Setter Property="RetryDelay" Value="250" />
</Style>
```

Let me know how it goes.

Best,
JP

**Comment by crakhi** [comment]
@jpbrocca Thanks for your quick response!

Yes I am using `VS Android Emulator` 

I tried replacing `<ffimageloading:CachedImage ... />` with  `<image>` and it worked!
I haven't tried on a Physical device - will check later. (Might take some time)

Thanks!

**Comment by jpbrocca** [comment]
Hi @crakhi, how are you?

It seems everything is working for you, so, I am closing this issue to keep things tidy, but feel free to reopen as necessary.
Thanks!

JP
