### ISSUE TITLE
Unable to Build Grial Template Project

### ISSUE THREAD

**Issue by ifegade** [UXDivers/Grial-UI-Kit-Support#166]
Downloaded the zip folder for both the starter and full template, restored all the nugets using the recommended url, but got the following compilation errors.. The name of the project is bizconnect..\

> Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'BizConnect, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'BizConnect.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	BizConnect.Droid	C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1064	

> Severity

	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\name\Desktop\Credentials\Full-BizConnect\Grial\BizConnect\bin\Debug\BizConnect.dll' could not be found	BizConnect.iOS	C:\Users\name\Desktop\Credentials\Full-BizConnect\Grial\BizConnect.iOS\CSC	1	Active

> Severity	Code	Description	Project	File	Line	Suppression State
Error		iOS theme colors definition file (ThemeColors.cs) not found in project 'C:\Users\name\Desktop\Credentials\Full-BizConnect\Grial\BizConnect\BizConnect.csproj'. (project 'C:\Users\name\Desktop\Credentials\Full-BizConnect\Grial\BizConnect\BizConnect.csproj').	BizConnect

**Comment by robertmclaws** [comment]
This was resolved in #164. Check the thread for the fix.

**Comment by wiltwitt** [comment]
I am getting this issue as well.  I get "iOS theme colors definition file (ThemeColors.cs) not found in project"  I do have ThemeColors.cs in ios project but error says that it can't find it from portable project.  I do have v2.0.35 on UXDrivers.  This is a Grial Starter project not mine.  I thought this issue was fixed???

**Comment by LeoHere** [comment]
@wiltwitt we released a preview version of the Nuget packages that fixes the ```ThemeColors.cs``` issue. In order to get it you must manually update the Nuget packages of your starter project. Those Nuget packages where released as Release Candidates, so in order to see them the "Show pre-release packages" option must be selected, as shown in the image bellow.

![image](https://cloud.githubusercontent.com/assets/16000584/24905688/2a628c4a-1e8b-11e7-8af3-82268106cfab.png)

You need to update the packages across the three projects.

If you download the starter project from the Admin site you still will get ```v2.0.35``` until we release the final version of the packages and update the site. That should happen in a couple of days.

**Comment by wiltwitt** [comment]
man, I feel like I am going crazy using this control.  I feel like I am spending more time trying to get this to work rather than writing my own code.....  Ok, so the example above seems like its for xamarin studio.  I am using visual studio 2017.   I checked on include prerelease packages but 2.0.50-RC does not show.  Is there way to do this through console or am I missing something?  thanks

**Comment by ifegade** [comment]
are you sure you are point the nuget to this url http://nuget.uxdivers.com/grial?

**Comment by wiltwitt** [comment]
it does not show up for downloaded starter project from admin console/page but it does show for my project.  That is odd.
