### ISSUE TITLE
Adding a new PCL reference

### ISSUE THREAD

**Issue by crakhi** [UXDivers/Grial-UI-Kit-Support#197]
For the Grial 2.0 Sample solution if I added a new PCL project and then trying to give the reference of the new project to the main project, then I am getting the below error. Whats the best way to create another PCL reference project.
Basically I want to separate the Models and the Services into a separate PCL projects.

---------------------------
```
Unable to add a reference to project 'ClassLibrary3'. The targets of Portable Library project 'ClassLibrary3' are not the same or compatible with the targets of the current Portable Library project.
A Portable Library project's targets can be changed via the Library tab in the project's properties.

```

**Comment by LeoHere** [comment]
@crakhi issue is because Grial PCL is using profile 78 meanwhile by default new class libraries are created using PCL profile 111. In order to fix this issue you will need to set the two to the same profile. Changing the profile of a project will require you to remove all the Nuget packages in your project and re-add them. 

I would recommend you to change the profile of the new class library, since it will be much much simpler.

From the error message, it seems you are working in VS, right? In VS I don't know a way to change the PCL Profile other than uploading the project and editing the ```.csproj``` XML manually (in XS you have an option in the project properties). 
So do as follows:
1. Remove any nuget package from the new class library project.
2. Unload the project and edit it
3. Change the ```<TargetFrameworkProfile>Profile111</TargetFrameworkProfile>``` to     ```<TargetFrameworkProfile>Profile78</TargetFrameworkProfile>```.
4. Add the removed nuget packages back

**Comment by crakhi** [comment]
Worked!
