### ISSUE TITLE
Icons didn't appear

### ISSUE THREAD

**Issue by joselacerdasoares** [UXDivers/Grial-UI-Kit-Support#201]
I'm using VS Studio 2017 in MAC.
When I build de App The Icons Didn't Appear.

<img width="381" alt="screen shot 2017-07-10 at 09 53 09" src="https://user-images.githubusercontent.com/6877437/28019632-fc5c1960-6557-11e7-84d2-b37fc8165121.png">

**Comment by LeoHere** [comment]
@joselacerdasoares I guess you migrated to Forms 2.3.4.xxx, right? There are some breaking changes and issues that affects Grial. We are about to release a new update solving these issues. 

In this case the problem is in ```DashboardItemTemplate.xaml```, remove the ```Text="{Binding Shape}"``` from the ```Label``` at line 48. This binding is actually wrong. In previous versions of Forms this binding was ignored but that has changed.

Additionally you will notice some issues with colors, in particular the ```AccentColor```. This is related to [this](https://bugzilla.xamarin.com/show_bug.cgi?id=56030) bug introduced in Xamarin Forms 2.3.4. It has been fixed but still it is not available in the stable channel. In the context of Grial, the bug only affects how colors are resolved, in particular the Accent color. 

There is a workaround which consists on moving the accent color to the end of the Theme XAML file you are using.

So if you had this in the ```GrialLightTheme.xaml```

~~~
<ResourceDictionary ...>
	<Color x:Key="AccentColor">#FFDA125F</Color>
	<Color x:Key="BaseTextColor">#666666</Color>

        .... other colors
</ResourceDictionary>
~~~

You should move the accent color to the end of the file.

~~~
<ResourceDictionary ...>
	<Color x:Key="BaseTextColor">#666666</Color>

        .... other colors

	<Color x:Key="AccentColor">#FFDA125F</Color>
</ResourceDictionary>
~~~

**Comment by joselacerdasoares** [comment]
Thank You Leonardo. It Works.
