### ISSUE TITLE
TabControl - TabStripPlacement and styleclass - can't set based on platform (XAML)

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Grial-UI-Kit-Support#240]
Facing an error when trying to set OnPlatform tag for tabstripplacement (TabControl)
Need to set it on bottom for iOS and top for android. What can be done? Needs to know what typeargument for tabstripplacement.
![capture](https://user-images.githubusercontent.com/14857549/30289311-69b28b20-9749-11e7-8b5b-84d3ef007035.PNG)
![capture6](https://user-images.githubusercontent.com/14857549/30289360-8be5e994-9749-11e7-8697-27d1e3225770.PNG)

**Comment by khadeeja-alif** [comment]
I also face an error on ios build - Can't resolve effects. Have already added needed nuget packages in ios. 
![effects](https://user-images.githubusercontent.com/14857549/30311128-82e40ba6-97b1-11e7-91e8-421040bbde7f.PNG)

**Comment by khadeeja-alif** [comment]
The project builds only on hashing all effect tags in App.xaml file.

**Comment by LeoHere** [comment]
@khadeeja-alif 

In order to set the `TabStripPlacement` property using the `OnPlatform` you need to target the `TabStripPlacement` enum type as shown in the following XAML piece:

~~~
<tab:TabControl.TabStripPlacement>
   <OnPlatform x:TypeArguments="tab:TabStripPlacement" iOS="Bottom" Android="Top"/>
</tab:TabControl.TabStripPlacement>
~~~

**Comment by LeoHere** [comment]
@khadeeja-alif regarding the problem with effects, probably it is because the assembly containing the effects has not be loaded because it's not directly referenced from your code (this is a known issue/limitation of Xamarin Forms).

In order to workaround this include these two lines in the `AppDelegate` before the `LoadApplication`:

~~~			FormsHelper.ForceLoadingAssemblyContainingType(typeof(UXDivers.Effects.Effects));			FormsHelper.ForceLoadingAssemblyContainingType<UXDivers.Effects.iOS.CircleEffect>();
~~~

or just do 

~~~
var a = typeof(UXDivers.Effects.Effects);
var b = typeof(UXDivers.Effects.iOS.CircleEffect);
~~~

which is the same the `ForceLoadingAssemblyContainingType` helpers do but with a pretty name.

Hope it helps.

**Comment by khadeeja-alif** [comment]
Okay Thanks.!

**Comment by khadeeja-alif** [comment]
Now I'm having trouble with GridOptionsView. When i bind a set of images and labels. Only the labels are displayed in all  the tiles. And Only few images get displayed. The Images are directly given in project and I'm using FFImageLoading to display images.

**Comment by khadeeja-alif** [comment]
Also having trouble with styling Tabs in TabbedPage. How can i style the tabstrip of TabbedPage similar to TabControl.

**Comment by jpbrocca** [comment]
Hi @khadeeja-alif,
For the GridOptionsView are you using a similar approach to the dashboard with images on Grial sample?...That should work.

If you get some of the images loaded then the problem could be wrong image names.

About TabbedPage styling: in part this is why we created our own control, because there is no much you can do to customize it's appearance.

By the way, please close this issue about Tab Control and open as necessary ones for GridOptionsView.

Thanks!
JP

**Comment by khadeeja-alif** [comment]
Okay! Great. Yes when i followed the dashboard approach, got it.! Thanks!.

**Comment by muhaym** [comment]
@LeoHere 

In release mode, iOS app crashes if we use 

```
var a = typeof(UXDivers.Effects.Effects);
var b = typeof(UXDivers.Effects.iOS.CircleEffect);
```

and when the code optimisation is turned on. 

So for any one with the same issue, it is always wise to use

```
FormsHelper.ForceLoadingAssemblyContainingType(typeof(UXDivers.Effects.Effects));
FormsHelper.ForceLoadingAssemblyContainingType<UXDivers.Effects.iOS.CircleEffect>();
```

**Comment by LeoHere** [comment]
@muhaym ok, thanks for shearing!
