### ISSUE TITLE
GridOptionsView - Screen Orientation , Padding and Row Issue

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Grial-UI-Kit-Support#245]
The GridOptionsView doesn't change its Scroll Orientation, on landscape.  How do I do this? 
And can the gridoptionsview fill the specific grid with needed no. of rows , rather than me giving a fixed no. of rows. When i give the no. of rows different in potrait and landscape there seems to lots of padding coming. 
![ggh](https://user-images.githubusercontent.com/14857549/30544209-60fdf988-9ca3-11e7-9d94-82ad7d2a74ae.PNG)
![fgsfg](https://user-images.githubusercontent.com/14857549/30544208-60f73d1e-9ca3-11e7-96f6-2648d210d51f.PNG)
So, how can i change the scroll orientation when its landscape. i want it to allow horizontal scrolling in landscape mode with no unwanted padding.

**Comment by jpbrocca** [comment]
Hi @khadeeja-alif,

it is not clear to me what you are trying to achieve.

> The `GridOptionsView` doesn't change its Scroll Orientation, on landscape

...`GridOptionsView` doesn't have any "Scroll Orientation" property.

You must include a `GridOptionsView` inside a `ScrollView` which will be the one handling scrolling if there is content to be scrolled. By default the `GridOptionsView` will tend to fill all available space so that could be part of your issue (you expect something to go off the screen while it is somehow elastically fitting content.

Can you post screen shots showing what you would like to achieve and your current result?

Best,
JP

**Comment by ImmenseIT** [comment]
Hi JP

We are using the Dashboard Scrollable as our home or master screen for the app we are building. 

Two issues Khadeeja mentioned above, 

First I have attached the screen to show how the tiles are not being aligned on the dashboard scrollable  page in our design. 
![test](https://user-images.githubusercontent.com/30938367/30565164-490aa29e-9c95-11e7-803c-d2105b0f62c0.jpg)

Secondly the for some reason when you flip the phone from verticle to horizontal the page gets squeezed up instead of being responsive to horizontal format. Khadeeja can share the screenshot for that as i missed to take one. 

Thanks for the help in advanced JP. 
Imran.

**Comment by jpbrocca** [comment]
Hi @ImmenseIT, how are you?

I have replied your emails about this issues.
Please let me know how it goes.

Best,
JP

**Comment by ImmenseIT** [comment]
Thanks Juan will do. Much appreciated.

Thank you
Imran Pathan
Director | Immense Inc. | info@immenseit.com<mailto:info@immenseit.com>
Toronto ON Canada


On Sep 18, 2017, at 7:05 PM, jpbrocca <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ImmenseIT<https://github.com/immenseit>, how are you?

I have replied your emails about this issues.
Please let me know how it goes.

Best,
JP

**Comment by khadeeja-alif** [comment]
Hi , 
I am sorry i think i got the images send in the wrong order. It is actually a gridoptionsview inside a scrollview. I am trying to change the scroll orientation on landscape. Is that possible?  I have mailed the correct xaml files and the trouble i'm facing.

**Comment by jpbrocca** [comment]
Hi @khadeeja-alif,

I double checked my email but I still didn't get the XAML files.
Could you please check?

Thanks
JP

**Comment by ImmenseIT** [comment]
Hi Juan


Is there a way we can have a webex or remote session for couple of issues that Khadeeja and team is facing.

I can send the webex if needed or if you have any other option would really help us move forward with project.


Thank you.

Imran Pathan

Immense Inc | info@immenseit.com



________________________________

**Comment by jpbrocca** [comment]
Hi @ImmenseIT, how are you?

Due to time constraints, I prefer you guys send me the files and please include a detailed explanation of what your issue is and what you need to achieve. That way we can help you faster (as the fixes we sent you yesterday after your email). If your explanation is not descriptive enough then we can only try guessing which is inefficient for both of us.

If sending the files and explanations is not enough, we can try to make a call or something but most probably this would be possible by end of this week. 

By the way, I have still not received the XAML files related to this issue.

Best,
JP

**Comment by ImmenseIT** [comment]
The xaml page is attached in my email. Will resend now.

Imran Pathan
Immense Inc. | info@immenseit.com<mailto:info@immenseit.com>

On Sep 19, 2017, at 12:53 PM, jpbrocca <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ImmenseIT<https://github.com/immenseit>, how are you?

Due to time constraints, I prefer you guys send me the files and please include a detailed explanation of what your issue is and what you need to achieve. That way we can help you faster (as the fixes we sent you yesterday after your email). If your explanation is not descriptive enough then we can only try guessing which is inefficient for both of us.

If sending the files and explanations is not enough, we can try to make a call or something but most probably this would be possible by end of this week.

By the way, I have still not received the XAML files related to this issue.

Best,
JP

**Comment by jpbrocca** [comment]
I have checked again and I cannot find any XAML.
Could you please notify me here when you send the email again?

Just in case, send it to:

![image](https://user-images.githubusercontent.com/15996999/30605116-50c3ab94-9d43-11e7-8093-e8c301b8861d.png)

Best,
JP

**Comment by ImmenseIT** [comment]
Attached is the zip file JP.

Also if you can send the webex for a convenient time would help, even if its at the end of week so at least if we cant resolve these issues by than then we can do webex to resolve them with your expertise.


Imran Pathan

Immense Inc | info@immenseit.com


________________________________

**Comment by ImmenseIT** [comment]
JP


I have attached all the XAMLs in question here please use this zip file instead.


Imran Pathan

Immense Inc | info@immenseit.com


________________________________

**Comment by jpbrocca** [comment]
I see what is the problem.
You are replying through email to Github notifications, this will sync this issue(#245) with your email but it won't work as an email.

Please send email with your attachments to my email address directly:
![image](https://user-images.githubusercontent.com/15996999/30605743-afc42004-9d45-11e7-8952-199b3619f9c9.png)

Thanks,
JP

**Comment by jpbrocca** [comment]
Hello @khadeeja-alif and @ImmenseIT, how are you?

I have replied your emails with my suggestions to fix your issues in your XAML code.
Please remember to close this issue and help us to keep things tidy!

Regards and thanks!
JP

**Comment by khadeeja-alif** [comment]
Hey, Doing Fine.
i wanted to know whether i could have the responsive helper - artina:OnOrientation property for ScrollView? It doesn't seem to change its value on Landscape.

**Comment by jpbrocca** [comment]
Hi @khadeeja-alif,

No, we don't provide a responsive helper for `Orientation` type as stated in Grial docs:
https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-helpers-responsive-helpers

> All can be used in conjunction with the following types:
`Int|Color|String|Bool|LayoutOptions`

Perhaps, as a workaround, you can set the `Orientation="Both"` ?

Best,
JP

**Comment by khadeeja-alif** [comment]
Thanks, Yeah that worked for the orientation. But Having issues with RowSpan - OnOrientation LandscapePhone Value. I have mailed you the File. Please do check it.

Regards,
Khadeeja
