### ISSUE TITLE
Icon on a Button

### ISSUE THREAD

**Issue by joselacerdasoares** [UXDivers/Grial-UI-Kit-Support#250]
How can I put a Icon (like "{ DynamicResource ChatIconButtonSendStyle }") in a Button or artina:Button?

**Comment by jpbrocca** [comment]
Hi @joselacerdasoares,
You can try something like this:

```
<artina:Button  
    HorizontalOptions="Start"
    WidthRequest="44"
    FontSize="26"
    Text="{ x:Static local:GrialShapesFont.Send }" 
    FontFamily="{ StaticResource IconsFontFamily }"
    Style="{ StaticResource PrimaryActionButtonStyle }"
/>
```
Notice I have set a `WidthRequest` same as Button's Height,  and `HorizontalOptions="Start"` to get a circular button:

![image](https://user-images.githubusercontent.com/15996999/30649237-254afb08-9df6-11e7-8120-83cd4cf03c50.png)

Otherwise, you will get a full block button:

```
<artina:Button  
    FontSize="26"
    Text="{ x:Static local:GrialShapesFont.Send }" 
    FontFamily="{ StaticResource IconsFontFamily }"
    Style="{ StaticResource PrimaryActionButtonStyle }"
/>
```

![image](https://user-images.githubusercontent.com/15996999/30649461-b50fc4da-9df6-11e7-8093-7913f120272a.png)

Best,
JP

**Comment by jpbrocca** [comment]
Closing this issue to keep things tidy.
Please reopen if necessay.
