### ISSUE TITLE
Styling status bar gradient and Entry

### ISSUE THREAD

**Issue by RasAndresI** [UXDivers/Grial-UI-Kit-Support#253]
Hi guys!

I know this isn't probably a serious issue... But when we're talking about UI and Style the customer complains so much.

Well... First problem is about status bar gradient image. When I deploy to Android Emulator it shows successfully status_bar_gradient.png as shown in   http://grialkit.com/screenshots/    SimpleLoginPage.
But when I deploy to Android device the gradient image is not shown.

On iOS simulator gradient image is shown correctly. Right now I didn't test on a real iOS device.

Second problem is Entry control style. Talking about the same view (SimpleLoginPage) the screenshot in Grial web site shows rounded border entrys, but it really don't look like that. Only shows bottom border.

I've downloaded Grial app from Playstore and it also shows only bottom border.

Thanks in advance.

**Comment by jpbrocca** [comment]
Hi @RasAndresI,

### About the SimpleLoginPage issue:

You are right! It seems that there is some bug on Xamarin Forms which is causing the AbsoluteLayouts to behave weird on Android (on iOS as you pointed it works OK).

Fortunately, there is a workaround:

1. Open your `SimpleLoginPage.xaml` file.
2. Replace your opening and closing `<AbsoulteLayout>` element with a `<Grid>`. Look at the diff below:
![image](https://user-images.githubusercontent.com/15996999/30672281-f1369b82-9e41-11e7-9e04-ebc914ae3b08.png)

3. Replace your image with the following:
```
<!-- GRADIENT-->
<Image
	Style="{ StaticResource StatusBarShimStyle }" />
```
4. Change in your `App.xaml` the `StatusBarShimStyle` as follows:
```
<!-- STATUS BAR GRADIENT -->
<Style x:Key="StatusBarShimStyle" TargetType="Image">
	<Setter Property="Source" Value="status_bar_gradient.png" />
	<Setter Property="VerticalOptions" Value="Start" />
	<Setter Property="HorizontalOptions" Value="FillAndExpand" />
	<Setter Property="Aspect" Value="Fill" />
	<Setter Property="Opacity" Value=".7" />
	<Setter Property="HeightRequest" Value="44" />
</Style>
```

Here is the diff:

![image](https://user-images.githubusercontent.com/15996999/30672312-1d1fb3d2-9e42-11e7-9909-e49f504e4f6e.png)

### About the Entry styles

The screen captures on our website are from iOS and the `<Entry>` elements used are the native control, which on iOS is renderer with rounded corners.

On Android the  `<Entry>` elements are renderer with the line at the bottom so that is why you get that outcome.

Best,
JP

**Comment by RasAndresI** [comment]
Thank u so much for ur help JP
I'll implement the workaround
Also thanks for the Entry style clarifications

**Comment by jpbrocca** [comment]
Hi @RasAndresI,
You are welcome!

Please remember to close the issue after you try the proposed solution.

Best,
JP

**Comment by jpbrocca** [comment]
Closing this issue to keep things tidy.
Please reopen if necessary.
