### ISSUE TITLE
iOS Back/Text Samples Gone

### ISSUE THREAD

**Issue by babernethy** [UXDivers/Grial-UI-Kit-Support#254]
![screen shot 2017-09-20 at 10 24 24 pm](https://user-images.githubusercontent.com/3207230/30676163-aa34f54c-9e52-11e7-9012-cfaa06d53e5e.png)

Not sure if it's just me, but it looks like the samples "back navigation button" (upper left) is gone with the update to iOS 11 - seems to be there in the AppStore version of the app, but not the downloadable sample from the template ...

**Comment by LeoHere** [comment]
@babernethy the problem seems to be that the buttons has the same color as the NavBar, thus we can't see them.

There is a workaround which is overriding the UI Appearance setup done by Grial. This can be done by passing `null` as the theme color in the `GrialKit.Init` and manually configuring all the appearance properties except the one for the `UIButton` which is the one causing the issue. In code it is as follows:

~~~
UXDivers.Artina.Shared.GrialKit.Init(null, ".....");

var colors = new ThemeColors();
var accentColor = colors.GetColor("AccentColor");

UIProgressView.Appearance.ProgressTintColor = accentColor;

UISlider.Appearance.MinimumTrackTintColor = accentColor;
UISlider.Appearance.MaximumTrackTintColor = accentColor;
UISlider.Appearance.ThumbTintColor = accentColor;

UISwitch.Appearance.OnTintColor = accentColor;

UITableViewHeaderFooterView.Appearance.TintColor = accentColor;

UITableView.Appearance.SectionIndexBackgroundColor = accentColor;
UITableView.Appearance.SeparatorColor = accentColor;

UITabBar.Appearance.TintColor = accentColor;

UITextField.Appearance.TintColor = accentColor;

//UIButton.Appearance.TintColor = accentColor;
//UIButton.Appearance.SetTitleColor(accentColor, UIControlState.Normal);

UIStepper.Appearance.TintColor = accentColor;
~~~

Still it is not clear the root cause of the issue and we still need to check the implications of commenting those two lines...

**Comment by babernethy** [comment]
That is working .. will try to see what the full impact of that is, but it appears to be showing up ...

**Comment by alexstrong29** [comment]
We had this issue, and it almost feels like iOS was actually fixing something that made it appear broken. Our accent color was actually the same colour as the UIButtons but in previous versions of iOS they appeared white. So we did the opposite to the above and overrided the UIButton color instead to white

```
private void iOS11Workaround()
        {
            var colors = new ThemeColors();
            var accentColor = colors.GetColor("HeaderAccentColor");

            UIButton.Appearance.TintColor = accentColor;
            UIButton.Appearance.SetTitleColor(accentColor, UIControlState.Normal);

        }
```


We added HeaderAccentColor to the ThemeColors class and it started working
{ "HeaderAccentColor", Color.FromHex("#FFFFFF") },

**Comment by babernethy** [comment]
This is actually fixed in the latest version of the Nuget packages from UXDivers - was able to remove the workaround before publishing to AppStore recently.

**Comment by alexstrong29** [comment]
One of my colleagues said this but I couldn't see the issue was fixed. Unless my Nuget is not finding the update? 
![capture](https://user-images.githubusercontent.com/10114151/32281008-74691bbc-bf15-11e7-8785-a05634288b17.PNG)

**Comment by babernethy** [comment]
If you look on the "Updates" tab does a 2.5.x? show up? I don't have my development machine here ...

**Comment by arthurmoreiraSD** [comment]
With two lines and for me it worked.

Thank you.

//UIButton.Appearance.TintColor = accentColor;
//UIButton.Appearance.SetTitleColor(accentColor, UIControlState.Normal);
