### ISSUE TITLE
iOS splashscreen

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#257]
Hello,

I tried to change the background color of the splashscreen on iOS, but I would like to know if it's possible to bound the color to a predefined color, like on Android.

I've followed the suggestion you given on another [issue](https://github.com/UXDivers/Grial-UI-Kit-Support/issues/228) and it works fine: I can define the color handly.

**_However, is there a way to bound the color directly on a "theme color", like on Android, instead of typing the values?_**

**Comment by jpbrocca** [comment]
Hi @Goldstrike, how are you?

Unfortunately, it is not possible because out of the box to bound the color to a theme color.
We will add a similar mechanism as in Android to make it happen on iOS (for next version).

I am closing this issue since it seems you finally made it work, but please feel free to re open as needed.

Best,
JP

**Comment by Goldstrike** [comment]
Thank you @jpbrocca

**Comment by jpbrocca** [comment]
You are welcome @Goldstrike ! :)
