### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by Bel0425** [UXDivers/Grial-UI-Kit-Support#262]
Hi There,

I have just purchased a kit and following the instructions like nuget restore etc.
even after nuget store, getting build errors for forms like 
"The name 'InitializeComponent' does not exist in the current context	"

Could you please help me to resolve this issue.

Regards,
Salil Belapurkar

**Comment by johncdoherty** [comment]
Check the file properties of the xaml.cs file and compare to other files of the same type. If I remember right, sometimes the values get cleared out. Otherwise, verify the xaml and xaml.cs files have the same namespace.
John

**Comment by Bel0425** [comment]
Project is getting build successfully but when i ran it then i get error for all opened pages like "The name 'InitializeComponent' does not exist in the current context".

As suggested, i have verified the namepaces for XAML & XAML.cs and both are same.

Any other clue?

**Comment by LeoHere** [comment]
@Bel0425 After the successful build, are you able to execute Grial? Are you using VSMac or VS? Which version? 

This `InitializeComponent` issue can be also because there were issues restoring Xamarin Forms packages. One thing you can try is to:
- close your IDE, 
- manually remove the `packages` folder (located next to the Grial solution file) 
- open the IDE again.
- restore all packages
- rebuild & run

Hope it helps.

**Comment by Bel0425** [comment]
Thank you so much.
I am able to run app after applying above steps.

**Comment by jpbrocca** [comment]
Closing issue
