### ISSUE TITLE
Production Mode License Error

### ISSUE THREAD

**Issue by ekangal** [UXDivers/Grial-UI-Kit-Support#276]
Hello,

When I try to download the license produced in production mode, it generates new license every time. I get an error when I use this license in the android project. The IOS project works fine with the old license. I get an error when I try the old license in the android project. I even get errors with old and new licenses in the grial starter project.

Which license should I use? Thanks in advance.

ERROR : UXDivers.Artina.Shared.LicenseException: License verification failed because: The PackageName does not match the license's.

•	License Mode: Production

![picture1](https://user-images.githubusercontent.com/3465364/31500704-d18be3ce-af70-11e7-8e14-d8dc5ef93d49.png)
![picture2](https://user-images.githubusercontent.com/3465364/31500705-d1b02fea-af70-11e7-9850-0164db7f4974.png)
![picture3](https://user-images.githubusercontent.com/3465364/31500706-d1d8e0e8-af70-11e7-8b63-87f70dab92d4.png)
![picture4](https://user-images.githubusercontent.com/3465364/31500708-d1ff4a80-af70-11e7-9a07-945d48a0f664.png)
![picture5](https://user-images.githubusercontent.com/3465364/31500709-d221b8c2-af70-11e7-83ca-dff3e5f6f338.png)
![picture7](https://user-images.githubusercontent.com/3465364/31500710-d2409e2c-af70-11e7-87fa-c8d3e88c345f.png)
![picture8](https://user-images.githubusercontent.com/3465364/31500711-d2602ea4-af70-11e7-9568-32eda8eb0157.png)

**Comment by LeoHere** [comment]
@ekangal I was able to reproduce the issue. 

I think that Android requires the package name to have at least one dot. If you check the package name of your app at runtime it returns "Ebys.Ebys", which do not march with "Ebys" and because of that the error you get. Seems that Xamarin or Android adds a "." if it found you did not added a dot.

The easiest way to fix it is to change the package name to something with a dot. If that is ok with you send me the package name to l r o d r i g u e z at uxdivers.com and I will do it for you (since you are in production mode and you will not be able to change it).
