### ISSUE TITLE
UXDivers.Artina.Shared.IsPortrait

### ISSUE THREAD

**Issue by pboisso** [UXDivers/Grial-UI-Kit-Support#278]
Hi Guys,

I would like to use UXDivers.Artina.Shared.IsPortrait property in the code-behind in this fashion : 

if( UXDivers.Artina.Shared.IsPortrait )
{
//do something for portrait only.
}

How would I do that?  Could you please provide an example on how to use orientation feature in the code behind, I have just found XAML samples so far.

Thanks.

Patrice

**Comment by LeoHere** [comment]
Hi Patrice,

`IsPortrait` is a markup extension that uses `IDeviceOrientation` service in order to know if it is portrait or not.

`IDeviceOrientation` can be obtained by using `IDeviceOrientationLocator` through the `DependencyService`.

In plain code:

~~~
var locator = DependencyService.Get<IDeviceOrientationLocator>();
if (locator.Service.IsPortrait)
{
 // do something portrait only
}
~~~

Hope it helps.

**Comment by pboisso** [comment]
Ah! Thanks!

**Comment by LeoHere** [comment]
Closing the issue. Feel free to open it again if you have any other question.
