### ISSUE TITLE
Image Sizes

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#289]
Hi,
Having some problems with images sizes - if I wanted a full width image - what image sizes would I need to generate so that it looked correct on mobile/tablet landscape/portrait?

Many Thanks!

**Comment by jpbrocca** [comment]
Hi @qaliwebguru,

That would depend on what you are using/trying to achieve. Normally images will tend to adapt to available size unless specified.
Could you elaborate more on what problems are you experiencing?

If you want to take full control of how things layout on page (on tablets, phones, and different orientations) and their sizes, you should check the **Responsive Helpers** docs:
https://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-helpers-responsive-helpers

Best,
JP

**Comment by qaliwebguru** [comment]
There are different issues we are facing. 

It would be nice if you could comment on following

1- In Grial Android, We can't see all size folders like Ihdpi & mhdpi etc? Is there any reason for this?
2- Some of the images in Grial image folders are with dimensions of 2808 x 1299. Isn't it too big for any device?
3- Why we can't see always x1, x2 anx  x3 images?
4- Do we need to use helpers all the time to deal with images if we use Grial?

Generally when we create any image for background or an image to put in the middle of the page, what should be the size which should fit all devices? Or we have to do it with responsive helpers?



Thanks

**Comment by jpbrocca** [comment]
Hi @qaliwebguru,

Let me start by explaining that Grial is relatively big app because it contains lots of images (one of our goals is that it should look great). 

As we added more content to the product we needed to add more images (Grial is optimized for tablets and phones). At some point we needed to make decisions and remove some of them in order to keep the app size as small as possible.

That could be the reason why you don't see all images in all different resolutions. But that was our strategy for our own app, you can add as many as you needed to achieve your market goals. You will be using your images in your final app so probably you will delete most of the ones provided with Grial.

Now about your questions:

1. As I mentioned above in some context it doesn't make sense to support low resolution drawables. Moreover, check this info from android:
https://developer.android.com/about/dashboards/index.html
The Screen Size and Density dashboard is a page provided by Google that provides data on breakdown of the screen size/screen density matrix. This breakdown provides insight on how to development effort on supporting screens.
2. Probably those are images used for tablets with high resolution. We also use the great ffimageloading library which does a great job optimizing images (downsampling, etc.) specially for Android.
3. That is probably for the strategy mentioned above.
4. Not at all. That will depend on your goals. The responsive helpers are a flexible and easy way for you to target specific scenarios and get more control on what you can do. That way you could use an specific image for phones portrait only and for the all other cases just a common image. Or, you could use specific images for tablets in landscape orientation. Again, depending on your goals that would make sense or not, for.example if you are using a blurred image as a background it won't probably make much sense to create all different resolutions and landscape/portrait combinations and use the responsive helpers to specify them!

Hope that helps.

Best,
JP
