### ISSUE TITLE
Splash screen with Localised text ?

### ISSUE THREAD

**Issue by MichelMatthey** [UXDivers/Grial-UI-Kit-Support#299]
Hi,

I need to be able to add some text to the splash screen and I need to use i18 to translate it before it gets there, fairly simple but I can't seem to see where and how it is done please ?

Can you please give me an example (code) on how I can:
1) Add a fixed piece of text below my splash image
2) How the translation works as this is not in the PCL where all my language resources are 

Please see the current Splash screen, the desired splash screen attached and the splash_drawable.xml file content...

**Please don't close this ticket until after it has been resolved!**

splash_drawable.xml:
<?xml version="1.0" encoding="utf-8" ?>
	<layer-list
	 	xmlns:android="http://schemas.android.com/apk/res/android">
		<item>
			<shape android:shape="rectangle">
				<solid android:color="@color/ComplementColor" />
				<padding 
					android:left="0dip" 
					android:top="0dip"
					android:right="0dip" 
					android:bottom="0dip" />
				</shape>
		</item>
		<item>
			<bitmap android:src="@drawable/splash"
			android:gravity="center" />
		</item>
	</layer-list>

<img width="218" alt="currentsplashscreen" src="https://user-images.githubusercontent.com/7455699/32082968-1f979b26-bb0b-11e7-9060-129322efd411.png">

<img width="218" alt="desiredsplashscreen" src="https://user-images.githubusercontent.com/7455699/32082972-25e9cb0c-bb0b-11e7-82c2-15abca7f113f.png">

**Comment by jpbrocca** [comment]
Hi @MichelMatthey, it seems you accidentally closed your previous bug about the same issue? #294

**Comment by MichelMatthey** [comment]
Yes, I thought someone else did... Anyway, can we get some answer please ?

**Comment by jpbrocca** [comment]
Hi @MichelMatthey ,
Xamarin Forms does not have any functionality to add a splash screen, you must do this per platform.
Normally you want the splash to be displayed fast and to be static, otherwise it will make no sense to delay things more to show the splash itself.
The most common approach is to show an image which will be easy and fast to be displayed while your app bootstraps. In that sense, if you need to show text the best practical/efficient alternative is to include them on your splash image. Then, you can localize images as I explained on #294 .

If for some reason you need to wait after app bootstraps you can the go with Xamarin Forms (XAML) and show an intermediary page with your texts localized as in any Grial page.

Best
JP

**Comment by MichelMatthey** [comment]
Can you please show us sample code that shows how it is done in both Android and IOS ? 

Support is what we are after here, I can google other things but this one is part of the Grial pages (And is somehow not documented!) so we need to know (And be given proper instructions and examples) how it is done, please provide a sample with dummy text and dummy translated text ? Just look at my screenshots, the current and desired ones...

All we need is for you to fill the blank in the existing xml file and any other piece of code that needs to be changed please, same for IOS ?


Thanks!

**Comment by logikonline** [comment]
jpbrocca - actually if you did my previous issue reported, it would enable MichelMatthey to be able to put the localization immediately after the splash screen shows by transitioning it to a page for us to manage.

It really would help a lot of us out.

**Comment by MichelMatthey** [comment]
Can you please spell it out, just show us the changes required to:
1) Add a bit of static text below the image
2) Change it so it gets translated

These are very small changes but we do need support as it is not obvious, please send us a sample bit of code (xml file changes + translation code + whatever else is required) as we can't work it out with what you have given us!

Please do not close this ticket until we get some sample code and solution!

Thanks very much!

**Comment by LeoHere** [comment]
Localizing the splash screen is a platform specific thing. Unfortunately, I don't think it is possible to localize it by just adding some lines in the drawable. That would be great for sure :), but adding text to a drawable is not that easy, see [this](https://stackoverflow.com/questions/23299552/text-with-shapes-in-drawable-resource) and [this](https://stackoverflow.com/questions/21822526/can-we-add-text-to-a-drawable) for example.

The splash screen Grial provides follows the best practices out there and covers the most typical scenario for our customers which is just to show an image (normally they put their app logo there). What you are asking is not supported in Grial, thus, you won't find any docs about it. As a side note, it even not recommended by Apple in their [human interface guidelines](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/launch-screen/):

>Avoid including text on your launch screen. Because launch screens are static, any displayed text won’t be localized.

Anyways, if it is a must for you doing so, probably the easiest way would be to add a localized image as suggested [here](https://developer.xamarin.com/guides/android/advanced_topics/localization/). In iOS you should be able to do a similar thing see [this](https://stackoverflow.com/questions/23934382/splash-screen-in-multi-language-ios-app). In iOS since it is a storyboard you should be able to add text (not localized).

Additionally, in Android, you could follow the path of extending drawable class to draw text yourself, as mention in the stackoverflow posts above. But I'm not sure how easy that path would be.

Finally, as @logikonline suggests, the other option would be to display an intermediate `xaml` page after splash ends and while you perform long tasks with your app. There you will be able the `Translate` extension as in any other page. However in that case the initial splash would not be localized at all.

Hope it helps.

**Comment by MichelMatthey** [comment]
No, that doesn't help either, a solution is what we are after, not maybes and try this and try that... 

You certainly shouldn't tell us what Apple wants, they don't dictate what 65% of the market does, they think they do but no they don't, Android (Google) is the one!

Don't worry I will place that stuff elsewhere on another page... Thanks anyway!

...Your competitors might offer a better support and more extensive functionality  ?

**Comment by logikonline** [comment]
@michelmatthey the solution I suggested is the correct way to do it. This enables you to allow the splash screen to show quickly and not localized in each platform. The transition to the Xamarin Forms splash page would then give you the ability to display the localized info seamlessly and offer additional features such as loading libraries and pages without triggering the timeout requirements for the app to start quickly. 

The only thing that would be needed from Grial is for them to make the intermediate splash screeen for us to use which is within their ability and would be a nice upgrade offering. But don't threaten them with competitors, there are none. The true competition is you become more skilled and take the time to do it yourself which is always an option. 

But I find Grial is very supportive if you take the high road.

**Comment by MichelMatthey** [comment]
All we wanted was to get a sample piece of code that works on IOS and Android, XAML forms or whatever, no can do so forget it, but that is not what we would call good support, anyone can do a "try this and try that or this But Apple says this etc" kind of response but that is not helpful at all, sample code and showing that you care enough to assist people who paid for a licence is what we were actually after. It was a very simple request requiring a very simple response. Thanks anyway, but we will not be recommending your product because of this lack of real support! No High road!

**Comment by MichelMatthey** [comment]
If you feel you can at last address this issue/question and show us some sample code that will work on IOS and Android please go ahead, much appreciated! Otherwise just close this ticket, Thanks!

**Comment by jpbrocca** [comment]
Hi @MichelMatthey, how are you?

Could you send me an email to jpbrocca@uxdivers.com so we can coordinate a call?

Regards and thanks,
JP

**Comment by MichelMatthey** [comment]
Hi JP,
Thanks for getting back to me, hopefully we can get to the bottom of this as the alternative solution of sticking the "Message of the Day" on another page instead of the splash screen doesn't make that much sense...

I am on Skype (Michel Matthey in Sydney, Australia) so call me anytime and I will respond if I am here. Note that in Sydney we are 10 hours ahead of GMT time.
Much appreciated
Michel
    On Wednesday, 8 November 2017, 12:33:47 pm AEDT, jpbrocca <notifications@github.com> wrote:  
 
 
Hi @MichelMatthey, how are you?

Could you send me an email to jpbrocca@uxdivers.com so we can coordinate a call?

Regards and thanks,
JP

**Comment by MichelMatthey** [comment]
After talking to Diego and Pablo from Grial on Skype, it is now clear, the splash screen is just to show an image and trying to do what I was requesting is simply too complex for now... 

Thanks guys for confirming that on our skype session, I will show a page with the information that was meant to go on the Splash screen instead...

Now closing this ticket
