### ISSUE TITLE
Problem about License : VisualStudio Previewer - Grial UI License not initialized, ...

### ISSUE THREAD

**Issue by gurhangulmez** [UXDivers/Grial-UI-Kit-Support#348]
Hi,

I have GrialLicense problem again,

This pictures illustrates the exception and my codes for license.

Can you help me to find where is the problem?

Thank You..

IOS :
![license](https://user-images.githubusercontent.com/13269673/35149457-337858ac-fd27-11e7-8f2d-1229f0c42c4d.jpg)

![code](https://user-images.githubusercontent.com/13269673/35149463-37921126-fd27-11e7-9bd1-c072b6505b7a.jpg)

**Comment by jpbrocca** [comment]
Hi @gurhangulmez, how are you?

The Xamarin Previewer has some limitations.
I suggest you try with [Gorilla Player](http://gorillaplayer.com) and Gorilla SDK which will allow you to preview Grial without issues. Please check the Grial docs about it:
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player

You can download your Grial Full or Starter projects from [Grial Admin](https://uxdivers.com/secure/grial/front) with Gorilla SDK preconfigured.

Best,
JP

**Comment by gurhangulmez** [comment]
Hi @jpbrocca , fine thanks, you?

I will use gorilla player, 

Thanks for your help

**Comment by jpbrocca** [comment]
Hi @gurhangulmez,

What do you mean?
Are you not being able to preview through Gorilla Player?

Best,
JP

**Comment by gurhangulmez** [comment]
Hi,
The problem is
After I select "Stick Gorilla to this" on a Xaml file, "Additional SDK
configuration needed" message comes up.




2018-02-26 18:12 GMT+03:00 jpbrocca <notifications@github.com>:

**Comment by LeoHere** [comment]
Hi @gurhangulmez,

Looks like you are using the player downloaded from the store, not Gorilla Player SDK.

You need to use Gorilla SDK. Did you downloaded Grial with Gorilla SDK preconfigured? [This](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player) shows you the workflow and give a step by step explanation of what needs to be done. 

Also, I suggest that you use the "Follow me" mode instead of the "Stick Gorilla to this".
