### ISSUE TITLE
TabControl's TabSlected Event

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#360]
Hi,

Looking at the TabControl's TabSelected eventHandler. Does it support command binding with ViewModel?

Below is my sample code. 

                     <tab:TabControl
                            TabStripPlacement="Bottom"
                            StyleClass="iOSTabControlStyle" **TabSelected="{Binding Handle_TabSelected}"** >
                            <tab:TabItem 
                                BadgeText="7"
                                IconText="{ x:Static local:GrialShapesFont.QueryBuilder }"
                        
                                Text="Profile"
                                >
                                <views3:ProfilePage/>                            
                            </tab:TabItem>

Visual Studio for Mac gives me error with the xaml code generated and indicate that "cast is not valid" error.

Error: Specified cast is not valid.

Please advice.
Dennis

**Comment by LeoHere** [comment]
@denfung in order to react to a tab change in your view model you can use two way binding with `SelectedIndex` or `SelectedItem` properties and react accordingly when they change. `TabSelected` expects a event handler, that is why you are getting the above error. We currently don't provide any `TabSelectedCommand` or similar.

**Comment by LeoHere** [comment]
Closing the issue now. Feel free to open it again is you need to.
