### ISSUE TITLE
How to change Active State TabStrip BackgroundColor

### ISSUE THREAD

**Issue by gurhangulmez** [UXDivers/Grial-UI-Kit-Support#362]
Hi,
I want to change a TabStrip BackgroundColor when its state is Active.

Isn't there a property name like TabStripActiveStateBackgroundColor?

I tried a lot of property name like this, but all of them failed and I couldn't find any documentation about it.

Thanks for your help

![strip](https://user-images.githubusercontent.com/13269673/35900186-9f368866-0be1-11e8-8e39-88a8ca861dfd.png)

**Comment by jpbrocca** [comment]
Hi @gurhangulmez, how are you?

There is no such property per se.
The reason is that Grial Tab Control is totally customizable through XAML templates.

So for example, if you want to change the tab item selected color you will need to edit the resources:

```
<Style x:Key="GrialTabItemIndicatorActiveStateStyle" BaseResourceKey="GrialTabItemIndicatorBaseStyle" TargetType="View">
    <!--<Setter Property="BackgroundColor" Value="{ StaticResource GrialTabItemActiveStateBackgroundColor }" />-->
    <Setter Property="BackgroundColor" Value="{ DynamicResource ComplementColor }" />
</Style>
```

In the above code, there is a specific resource used to set the background color.
It is commented because in the context of Grial sample we used the `AccentColor` resource, but you can use `GrialTabItemActiveStateBackgroundColor` resource -with any color-:

~~~
<Color x:Key="GrialTabItemActiveStateBackgroundColor">#525ABB</Color>
~~~

You will also find there are a bunch of other exposed colors that will allow you to further customize the TabControl:

~~~
<Color x:Key="GrialTabStripBackgroundColor">#66000000</Color>
<Color x:Key="GrialTabContentBackgroundColor">White</Color>

<Color x:Key="GrialTabItemDefaultStateBackgroundColor">Transparent</Color>
<Color x:Key="GrialTabItemDefaultStateTextColor">#FFFFFF</Color>
                
<Color x:Key="GrialTabItemActiveStateTextColor">#FFFFFF</Color>
~~~

Let me know if you have questions.

Best,
JP

**Comment by LeoHere** [comment]
Closing the issue. Feel free to open it again is you need to.

**Comment by IoTFier** [comment]
@jpbrocca , @LeoHere 

I don't see the style mentioned above in my App's Grial code. Was this removed in July or so (that's when I got my first cut of the Grial Code)?

<Style x:Key="GrialTabItemIndicatorActiveStateStyle" BaseResourceKey="GrialTabItemIndicatorBaseStyle" TargetType="View">
    
    <Setter Property="BackgroundColor" Value="{ DynamicResource ComplementColor }" />
</Style>

Where do I set it in the DataTemplate or in the TabControlStyle ? Can you share with me an example for this one and one for setting the background color of the default Tab Item?

Thanks

**Comment by IoTFier** [comment]
It seems the style key name was changed to call TabItemIndicatorActiveStateStyle.  I uncommented the background color property to assign a value using my color key. But the result is still not the same.
It looks like the background color of the TabBar strip shadows over the background color of the TabItem.
And I see only a underlying line for that TabItem. I will certainly use that underline (different color) but the background color needs to be the one from the style below. 
Currently it is not working.


	<Style
		x:Key="TabItemIndicatorActiveStateStyle"
		BaseResourceKey="TabItemIndicatorBaseStyle"
		TargetType="BoxView">
		<Setter Property="BackgroundColor" Value="{ StaticResource PrimaryTabItemActiveStateBackgroundColor }" />
		
	</Style>
