### ISSUE TITLE
Xamarin Live Player: Samples not working

### ISSUE THREAD

**Issue by voicebooth** [UXDivers/Grial-UI-Kit-Support#365]
Hi,

I just purchased the Pro kit, and have downloaded the full and starter samples to run on the latest version of iOS via Live Player, but Live Player is reporting an error along the lines of:

Cannot throw "UXDrivers.Artina.Shared.LicenseException"

What can I do to get the samples up and running?

**Comment by jpbrocca** [comment]
Hi @voicebooth, how are you?

Xamarin Live Player is still immature and have limitations.
I suggest you to use [Gorilla Player](gorillaplayer.com) which is free and will provide the best experience to work with Grial (we made Grial using Gorilla Player).

I am closing this issue now since it is a duplicate (Please check this related issue:
#348), but feel free to reopen if needed.

Best,
JP
