### ISSUE TITLE
License Exception Error.

### ISSUE THREAD

**Issue by szaid07** [UXDivers/Grial-UI-Kit-Support#384]
I have attached the error log ''UXDivers.Artina.Shared.LicenseException" please give some solution ASAP.

[XLP_Logs_18-03-12_15-36-02.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/1805548/XLP_Logs_18-03-12_15-36-02.txt)

**Comment by LeoHere** [comment]
Hi @szaid07, can you please provide more details about when are you getting this exception? 
- The Xamarin Live Player is mentioned in the logs. Does the exception happens only within the XLP?
- Does the exception happens when executing the app?
- When did this exception start to happen?

The logs does not shows the `LicenseException`'s companion message. It is crucial to see it since it usually specifically says what specifically goes wrong.

**Comment by eglibecerra** [comment]
This also started happening for me today... how long does the license last? do i need to refresh the license whats the go?

**Comment by eglibecerra** [comment]
just checked the admin it was an expired license...

**Comment by LeoHere** [comment]
@eglibecerra please read [this link](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-grial-first-run-license-modes) which explains how license mode work.

**Comment by LeoHere** [comment]
@eglibecerra please read this [link](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-grial-first-run-license-modes) which explains how license modes work.
