### ISSUE TITLE
enabledRemoteNotificationTypes not supported errors

### ISSUE THREAD

**Issue by sadranyi** [UXDivers/Grial-UI-Kit-Support#386]

**Comment by jpbrocca** [comment]
Hi @sadranyi,

in order to help us to understand your issue can you please let us know:

- Which version and flavor of Grial are you using?
- Which version of Xamarin Forms are you using?
- Which platform gives this error?

Also a little bit of context of when and how you get this error would also help.

Thanks,
JP

**Comment by sadranyi** [comment]
Version: v2.5.14-RC
Xamarin: 2.5.0.122203
Platform: iOS

The Application works fine in Android, just trying to run it on iOS and i keep running into this. I cant get past the splash screen

**Comment by jpbrocca** [comment]
Can you provide more context?

Is this happening in your Grial Starter or Grial Project?

**Comment by sadranyi** [comment]
Grial Project

**Comment by jpbrocca** [comment]
Did you add any third party package or this is just the Grial project you downloaded from Grial Admin?

**Comment by sadranyi** [comment]
just the Grial

**Comment by jpbrocca** [comment]
Could you try updating to latest Xamarin Forms and also to the latest version of Grial packages and let me know if the issue persists?

I downloaded both Grial Starter and Grial Full samples from Grial Admin, restored packages and updated to latest and I don't get any issue.

Best,
JP

**Comment by sadranyi** [comment]
Will try that.
