### ISSUE TITLE
Property FontSize is set more than once

### ISSUE THREAD

**Issue by samnaseri** [UXDivers/Grial-UI-Kit-Support#390]
Hi,

I have looked into your SignUpPage.xaml from the downloaded solution and noticed that it has defined FontSize property on some elements more than once (actually this is what Resharper complains about)

This is an example:
`
					<Label LineBreakMode="WordWrap" Text="{ artina:Translate LabelRegisterNowAndEnjoy }" TextColor="{ DynamicResource OverImageTextColor }" VerticalTextAlignment="Center" FontSize="36" AbsoluteLayout.LayoutFlags="All">
						<Label.FontSize> 
							<OnIdiom x:TypeArguments="x:Double" Phone="17" Tablet="27" />
						</Label.FontSize>
					</Label>
`

Why it is written this way? Can I rewrite this in a different way so that I don't get Resharper warnings? Can I turn off resharper warnings somehow?

**Comment by jpbrocca** [comment]
Hi @samnaseri, how are you?

You found a bug, this is simply a duplicated property which probably happened due to a merge on our end.

You can safely remove the `FontSize="36"` since the following block is the one setting properly the font size for phones and tablets:

~~~
<Label.FontSize> 
        <OnIdiom x:TypeArguments="x:Double" Phone="17" Tablet="27" /> 
</Label.FontSize>
~~~

Regards and thanks,
JP

**Comment by samnaseri** [comment]
Thank JP.
There was also some extra } after some Binding expressions which you might want to fix too.
