### ISSUE TITLE
How to bind artina:Translate and json data to same label 

### ISSUE THREAD

**Issue by szaid07** [UXDivers/Grial-UI-Kit-Support#409]
I am trying to bind the artina: translate and json text on a single label but I can't so I used to two labels in stack layout but because of this rtl mirroring is not working properly.

`<StackLayout Orientation="Horizontal" HorizontalOptions="Fill">
                                            <Label Text="{artina:Translate Centername}"  TextColor="#D28A4C" FontAttributes="Bold" FontSize="Medium" HorizontalOptions="Start"/>
                                            <Label Text="{Binding name}" x:Name="lblTitle" TextColor="#D28A4C" FontAttributes="Bold" FontSize="Medium" />
                                        </StackLayout>`

Can we bind it in one label.

**Comment by jpbrocca** [comment]
Hi @szaid07,

You cannot use a single `Label` to show two bindings.
You should somehowconcatenate both values and pass it to the label as a single binding.

Your StackLayout needs to be explicitly told to behave with the RTL mechanism, otherwise it won't mirror your layout.
Check the docs about how to make it RTL enabled:
http://uxdivers.github.io/Grial-UI-Kit-Support/rtl-page.html

Best
JP

**Comment by szaid07** [comment]
Hi ,
Stack layout is RTL enabled but it's not working.
