### ISSUE TITLE
Can't restore the solution 

### ISSUE THREAD

**Issue by imzuhdi** [UXDivers/Grial-UI-Kit-Support#417]
![error](https://user-images.githubusercontent.com/32406230/39086280-71d49b58-45b9-11e8-8605-18bd254050b0.JPG)
![ux](https://user-images.githubusercontent.com/32406230/39086293-931d7708-45b9-11e8-88c2-f2dbaa9a6c5b.JPG)

**Comment by LeoHere** [comment]
@imzuhdi If you are getting a 401 it mease the package source is correctly setup but the credentials are wrong. 

Tip: On easy way to verify your credentials is visiting [http://nuget.uxdivers.com/grial](http://nuget.uxdivers.com/grial) in your browser.

**Comment by imzuhdi** [comment]
@LeoHere where i can setting the credentials in VS 2017 in windows?

**Comment by LeoHere** [comment]
@imzuhdi it should ask you when you try to restore your packages. 

You can also check issue #376.

**Comment by imzuhdi** [comment]
@LeoHere  thank you.... 
is grial support live player previewing with app from xamarin?
cause when i run in xamarin live player, got error "Cannot throw UXDriver.Artina.Shared.LisenceException on thread 1 (NInterpretException)"

![whatsapp image 2018-04-25 at 23 57 42](https://user-images.githubusercontent.com/32406230/39260901-ffc26cdc-48e4-11e8-836a-783a74b7a2e5.jpeg)

**Comment by LeoHere** [comment]
@imzuhdi I can't say if the Xamarin Live Player support complex stuff as Grial because we use Gorilla Player as out main previewing tool in our XF projects. 

Did you know you can download Grial preconfigured with Gorilla SDK? That allows you to start previewing Grial in Gorilla Player. 

Please read [this](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player) section of the documentation for more information about this.

**Comment by imzuhdi** [comment]
@LeoHere  thanks...

in grial can i use the android tab control style and ios tab control style in one page?

**Comment by dirivero** [comment]
Yes, that's possible. You would use an on platform value to use one style or the other.

**Comment by dirivero** [comment]
I will close this issue as it's old and answered. Feel free to reopen or create a new one if needed.
