### ISSUE TITLE
Migration of Grial project?

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#425]
Hello,

We have purchased a Grial license on Jul 18, 2017. So we started to develop our app from the current version: I think that it was the v.2.0.60. We've already updated Xamarin.Forms packages to v.2.4.0.282.

I would like to know is there is a way to "migrate" our app to the latest version of Grial? (v.2.6.9.0)

**Comment by jpbrocca** [comment]
HI @Goldstrike, 
sorry for the late reply, we were very busy with Build conference.

Basically, if you go to Grial Admin, you could set the version to 2.0.60, then download the Full project.
Then you change to latest version and download again.
Finally, you can do a Diff of both projects to check the changes.

Also, you can check the [release notes](http://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html) of every release to get more details.

![image](https://user-images.githubusercontent.com/15996999/39934405-0bd98f44-551c-11e8-968c-d824825e7334.png)

Best regards,
JP

**Comment by jpbrocca** [comment]
Hi @Goldstrike,
What I mean is that by doing the described process you will get an idea which stuff changed from your version to latest. This is something you will do aside from your project.

Then, after the diff, you will need to incorporate those changes into your project.
Unfortunately, there is no other way to do this than manually.

I was talking about the Full project because I was under the assumption you wanted to see changes into views/pages also. You can try doing the same with a starter project, but most likely you will miss a few XAML changes.

Best,
JP

**Comment by Goldstrike** [comment]
@jpbrocca 
I understand better nown thank you!
Do you already know when the next GrialKit version supporting XF3 will be available? ;-)

**Comment by jpbrocca** [comment]
@Goldstrike,
you are welcome!

Nope, but I think it should be ready in the upcoming weeks.

**Comment by Goldstrike** [comment]
Hi @jpbrocca 
Any news about the support of XF3? ;-)

**Comment by jpbrocca** [comment]
Hi @Goldstrike, how are you?

Today we released Grial 2.7.0.0 with support for Xamarin Forms 3.1.

Best,
JP
