### ISSUE TITLE
Gorilla Player on Android crashes once started

### ISSUE THREAD

**Issue by sgiuffrida** [UXDivers/Grial-UI-Kit-Support#431]
I've downloaded the Grial Starter - Gorilla Ready solution from Grial Admin; I've also downloaded last version of Gorilla Player (server) 1.2.0.6 for Windows and I've installed the same version on my tablet; the MyCoolCompanyApp works perfectly.
When I try to see WelcomeStarterPage View of Grial Starter - Gorilla Ready the Android Gorilla Player crashes.
You can find log files attached.
Thanks in advance
Salvo

[gorillaHost.log](https://github.com/UXDivers/Grial-UI-Kit-Support/files/1995565/gorillaHost.log)
[gorillaPlayer.log](https://github.com/UXDivers/Grial-UI-Kit-Support/files/1995566/gorillaPlayer.log)

**Comment by jpbrocca** [comment]
Hi @sgiuffrida,

did you follow steps from this document?

http://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-previewing-grial-with-gorilla-player

From your comments, it seems you are running Gorilla Player to preview but you need to run Gorilla SDK embedded in your app in order to preview complex stuff like all the custom renderers in Grial, etc. You can do that by clicking on the Gorilla configuration here:

![image](https://user-images.githubusercontent.com/15996999/39934744-29c136dc-551d-11e8-990d-74e0b3ab114d.png)

More info here:
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK

Best,
JP

**Comment by sgiuffrida** [comment]
Hi JP,
you're perfectly right. Now it's working with no problem at all.
Thank you very much.
Best Regards
Salvo
