### ISSUE TITLE
After update projetct 

### ISSUE THREAD

**Issue by ClaudineiMonteiro** [UXDivers/Grial-UI-Kit-Support#460]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![capturar02](https://user-images.githubusercontent.com/16354515/43428805-861f00be-9436-11e8-9612-6f802d987d69.PNG)

**Comment by ClaudineiMonteiro** [comment]
![capturar03](https://user-images.githubusercontent.com/16354515/43429578-87b5ea7e-943a-11e8-96f0-abe6b9795220.PNG)

only this last image of the error remained

**Comment by LeoHere** [comment]
@ClaudineiMonteiro this is weird what version of Grial are you using?  Because `TransparencyEnabled` of `CachedImage` is not used in current version of Grial. It has been deprecated from `FFImageLoading` for a while now. See [this](https://forums.xamarin.com/discussion/52530/cachedimage-ffimageloading-for-xamarin-forms/p6) for more info.
