### ISSUE TITLE
Cant Delete app form Grial UI Kit admin

### ISSUE THREAD

**Issue by mostafasany** [UXDivers/Grial-UI-Kit-Support#509]
Cant delete app from Grial UI Kit admin

### Description
Removing created apps from Grial UI kit admin is not possible, 

### Steps to Reproduce

1. Open https://uxdivers.com/secure/grial/front/index.html#/myapps
2. Press Register new APP
3. Try to delete it

### Expected Behavior
There should be option to delete it

### Actual Behavior
Cant be deleted

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by LeoHere** [comment]
Hi @mostafasany,

You are right, currently we don't have a way to delete an app. However you can edit your current app, updating all its info (app name, bundle identifier, solution, namespace, etc), just as if you created a new app. 

Hope it helps.

**Comment by mostafasany** [comment]
But it says:
Currently you don't have any Grial license available to register a new app.
You can buy a new one from the buttons below:

**Comment by LeoHere** [comment]
@mostafasany 

That is because you are trying to create a new app and you don't have any unassigned license. You need to edit your current app by going clicking the app name (i.e. Grial UIKit in the image below) to go to its detail page. 

![image](https://user-images.githubusercontent.com/16000584/50526346-2dce3c80-0ac0-11e9-9d02-0b7c1a3e79ef.png)

While you are in the detail page you can edit everything:

![image](https://user-images.githubusercontent.com/16000584/50526378-6cfc8d80-0ac0-11e9-9c03-81b8a51eebe8.png)

The **App Settings** tab contains app identification data, meanwhile the **Solution Settings** has solution related stuff. 

Once you update those two with the info of the new app hit **Save**.

**Important:** your app must be in Development mode for this to be possible.

**Comment by mostafasany** [comment]
Unfortunately , its in production?

**Comment by MRashed** [comment]
Hi LeoHero,
we stuck with this issue in publishing to Apple store, and it's not reasonable to order new license just for rename app name, you can do all required actions to make sure we are using this license for same app, but order a new license is not a solution.

**Comment by LeoHere** [comment]
@MRashed If for some reason you can't publish your app with the current name or bundle we can help you changing it. There is no need to purchase an additional license, since the app is the same. Please write to hello at uxdivers.com explaining what changes you need and why you need them. We will follow from there.

I'm closing the issue. Feel free to open it again if you need to.
