### ISSUE TITLE
gorilla player issue not working

### ISSUE THREAD

**Issue by dogood45550** [UXDivers/Grial-UI-Kit-Support#511]
hello , i am using Gorilla Player version 1.1.0.4 and latest version of Visual Studio 2017 Gorilla Player work fine with Sample File but when i am create my own 
project its takes error " Please see the Log file Internal Error " any body Help me 

what things are Missing thats are not in my Project

**Comment by jpbrocca** [comment]
Hi @dogood45550,
Is this happening with your Grial project?

**Comment by dogood45550** [comment]
internal error when create new  project but its working with Sample files

**Comment by jpbrocca** [comment]
OK, I suspect you are in the wrong place.
Correct me if I am wrong, but this seems to be an issue not related to Grial UI Kit but with Gorilla Player, right?

Add your issue here:
https://github.com/UXDivers/Gorilla-Player-Support/issues

Please add more information. From What I understand you are using an old version of Gorilla Player.
Download the latest version and use Gorilla SDK embedded in your app, then, deploy it to your devices.

Check here for more details:
https://blog.xamarin.com/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/

I am closing the issue here to keep things tidy.

Best,
JP
