### ISSUE TITLE
some of the resources were missing in the app

### ISSUE THREAD

**Issue by danialbakhsheshi** [UXDivers/Grial-UI-Kit-Support#54]
when I lunch the application the picture fromimage dashboards are not showing, also the close button on top right is not there, in IOS it shows as question mark but in android it doesnt show at all.

**Comment by jpbrocca** [comment]
Hi @danialbakhsheshi,

are you testing over the sample provided when you download Grial ?
...or this is your own project?
If is the second, make sure you have properly referenced and included all necessary files:
https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/How-to-add-icons-to-your-project

From your comments, it seems you can see a question mark. That happens when you don't have the icons font properly set (the icons are actually the glyphs of a font, so no bitmaps are used).

Best,
JP
