### ISSUE TITLE
Grid Item Customization 

### ISSUE THREAD

**Issue by ZiaStansall** [UXDivers/Grial-UI-Kit-Support#555]
Hi i want to edit the ITEMS inside the Grid. Lets say... i want to make 9 items to 4 items and changing the icons on the  page ( 2 rows and 2 column), how can i do that in easy way? Thanks in advance!

**Screenshots**
![60f8e46f-49b9-4fdb-947c-54ed88e6975b](https://user-images.githubusercontent.com/49310231/55789235-7dbf9500-5aec-11e9-8807-05d58a9a2b1a.jpg)
![90d66c2d-9db0-43ef-9fd1-1133d1b7a9df](https://user-images.githubusercontent.com/49310231/55789237-7e582b80-5aec-11e9-825d-8298c2ee4290.jpg)

**Comment by jpbrocca** [comment]
Hi @ZiaStansall,

You can change the `ColumnCount` property to be "2", that will give you the 2 columns.
Then you must change the data used by the page to just display the 4 items you want (the number of rows will depend on the amount of items).

Open `DesignTimeData.json` file, search for `"DashboardItems"` and inside it the `"Items"` property.
If you change those items you will get what you need. 
I just removed 5 last items and here is the result:

![image](https://user-images.githubusercontent.com/15996999/55832504-1a356780-5aec-11e9-88f0-6442dfc792d3.png)

Regards,
JP

**Comment by ZiaStansall** [comment]
Nice! i have managed to do this as well. Thanks Much! Really appreciated (y)

**Comment by ZiaStansall** [comment]
Ok i am having another issue here.. which is the "ICONS". If i use code from GrialIconsFont.cs it works but if i use code from other .cs file like Material Community font then it does not work. How to solve it?

**Comment by jpbrocca** [comment]
Hi @ZiaStansall, how are you?

If you change the font helper to specify other glyphs you must also change the font family on the template's icon `Label` in order to get the right icon rendered.

**Comment by ZiaStansall** [comment]
Sorry i dont find the `Label1` on the xaml file

**Comment by jpbrocca** [comment]
Hello @ZiaStansall,

No, I am talking about the `<Label>` inside the XAML template that finally renders the icon.

**Comment by ZiaStansall** [comment]
Hi is there any complete user manual for customizing the UI kit? I am facing many other problems and need help on that.

**Comment by jpbrocca** [comment]
Hi @ZiaStansall

You can find the documentation here:
https://docs.grialkit.com

What are the problems you are experiencing?

**Comment by ZiaStansall** [comment]
Hi. 
I checked https://docs.grialkit.com before but dont find what i am looking for. The problems i am facing at the moments are given below:
- Making some other page as startup page
- how to add Grial Grid view on template page(xaml), so that it works fine as the demo app
- Changing alignment of the titlebar
- adding onclick functions on the tap

**Comment by ZiaStansall** [comment]
I have bought this app to speed up my project because i am running out of time but its taking a lot time to understand the coding... So badly need help!

**Comment by dirivero** [comment]
Hi,

I'm sorry to hear you are having trouble customizing Grial. I will try to anwser your questions: 

- Making some other page as startup page 
  There's a class called `MainMenuViewModel` that comes with the list of selected screens in Grial Web Admin (I recommend you to download a Starter Solution to see this code, the full solution is slightly different). In the constructor of that class the first entry of the `MainMenuEntries` list is used as the start, you can pick another.
- How to customize the Navigation Drawer Items and navigate to custom page
  In that same `MainMenuViewModel` class, the `MainMenuSelectedItem` property is how the app navigates to the selected item when the user taps one. Both the items and the selected items are bound to the UI through Bindings. You can read more about bindings and viewmodels here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/mvvm
- how to add Grial Grid view on template page(xaml), so that it works fine as the demo app
  There are examples on how to use the GridView control on Grial, can't you use as an example the page you were working with in your first question? You can read about the difference between Grial pages and templates here: http://docs.grialkit.com/overview.html#grial-3-overview-flows-pages-templates-and-themes-explained
- Changing alignment of the titlebar
  You can't change the alignment on the regular navigation bar. If you need to customize that you may need to use a Xamarin TitleView: https://devblogs.microsoft.com/xamarin/xamarin-forms-3-2-0-released-going-big-with-little-things/
- adding onclick functions on Grid Item
  Please check here https://github.com/UXDivers/Grial-UI-Kit-Support/issues/207
- How to add toolbar items
   Please check here https://www.youtube.com/watch?v=qv1X6eB0flw

I hope you understand that as Grial is delivered as a Xamarin.Forms project including the code of the pages, there's no limitation on how you combine and extend them but it requires some level of understanding of some platform building blocks such as bindings, viewmodels and xaml.

You can ping me directly to drivero at uxdivers.com if you want to discuss further.

Hope this helps.
Diego

**Comment by ZiaStansall** [comment]
Ok.. thank you for your reply. Le

- can't you use as an example the page you were working with in your first question?
  I am working with that. I have managed to show 4 icons (2 column) on the page. But now the problem 
  is how to switch to four different pages from those 4 icons tab?

**Comment by jpbrocca** [comment]
Hi, 
We have added more documentation about the GridView:

http://docs.grialkit.com/grid-view.html

You can check here for adding click to the items:

http://docs.grialkit.com/grid-view.html#working-with-the-gridview-samples-using-the-itemclickcommand

Regards
JP

**Comment by ZiaStansall** [comment]
Hi.. Thank you!
I have got this but what i meant is, i need separate action for each icon on my page. For example, if i tap on the "HOME" icon it will take to the home page and "Message" icon it will take to the message page. not just showing same message("YOU HAVE TAPPED ON DASHBOARD ITEMS") on every icons. Could you please tell me how to do that?  And again thank you so much for the information :)

**Comment by dirivero** [comment]
Take a look at this specific section: 
http://docs.grialkit.com/grid-view.html#working-with-the-gridview-samples-using-the-itemclickcommand

In the method `ItemAction(...)` of the ViewModel you receive the specific action object the user tapped so you can decide in code what to do, it you get the HOME you can navigate to the HomePage.

If you need to navigate to a specific page you need to call `Navigation.PushAsync(new SomePage())`
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical

ContentPages have the `Navigation` property that is used for this, you can pass it down to the viewmodel.

**Comment by ZiaStansall** [comment]
Hi.. i have done that and it works. Thank you! Now i'm having another problem which is pressing the item multiple times loading multiple pages. 

on the button click when i use the code below, it works. But what should i do with list item click? please help.
             this.IsEnabled = false;
            await this.Navigation.PushAsync(new NewPage());
            this.IsEnabled = true;

**Comment by dirivero** [comment]
You can define a private field in the view model to indicate if you can navigate or not:

`private bool _canNavigate = true;`

Set it to `false` before the push, and `true` after the push (same thing you do with `IsEnabled`).

Finally, wrap the `ItemAction` body with this check `if (_canNavigate)`.
