### ISSUE TITLE
Theme.AppCompact issue

### ISSUE THREAD

**Issue by navakiran5** [UXDivers/Grial-UI-Kit-Support#57]
Hello,
        I just purchased Garil UI Kit. I trying to build the project which is causing build issues.
![image](https://cloud.githubusercontent.com/assets/5318397/16856337/3e6a26cc-4a37-11e6-9d05-833aea34e171.png).

**Comment by jpbrocca** [comment]
Hi @navakiran5,
please take a look at the questions below to try to help us identify where your problem is:

- which version of Xamarin Forms are you using ?
- Did you make sure you restored packages ?
- Did you make a clean/rebuild before compiling ?
- Are you trying to compile Grial sample or your own project ?

Thanks,
JP

**Comment by navakiran5** [comment]
I am trying to compile Grail Project. I have restored the packages. I performed clean and build

**Comment by jpbrocca** [comment]
which version of Xamarin Forms are you using ?

**Comment by navakiran5** [comment]
2.2.0.31

**Comment by jpbrocca** [comment]
did you compiled the Colors.tt file ?
What do you have inside the Colors.xml file inside Android project ?
![image](https://cloud.githubusercontent.com/assets/15996999/16857287/456e6434-49f5-11e6-9999-d922b468f45a.png)

**Comment by navakiran5** [comment]
![image](https://cloud.githubusercontent.com/assets/5318397/16857476/9443e5dc-4a3d-11e6-9b6c-41e8a0c619bc.png)
I didn't compile it. I don't have xamarin studio installed. But the error is
**Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.**

**Comment by jpbrocca** [comment]
You can compile the Colors.tt through Visual Studio too.
I asked about this because from your previous screen shot you had an error about the color resources used on Android theme (colorAccent for instance).

Can you check that your Packages folder on Android project is not showing any issue with some of the packages ?

![image](https://cloud.githubusercontent.com/assets/15996999/16857880/3f730ff4-49f9-11e6-8c34-7c2cd7b852ab.png)

**Comment by navakiran5** [comment]
@jpbrocca I have resolved the issue. The issue is with cache of the packages in AppData of my system. I Removed those from AppData folder and restored all the packages.

**Comment by jpbrocca** [comment]
Hi @navakiran5 .
OK, thanks for letting us know.

Best,
JP
