### ISSUE TITLE
GrialNavigationPage

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#574]
Hi Grial Team,

This is neither issue nor feature request.

I would like to know it is possible to have NavigationPage transparent only at certain pages.
I created a custom GrialNavigationPage with transparent with Prism framework. 

Anyway I can turn on/off this "Transparency" dynamically when navigate to specific page? 

Please advice.
Dennis

**Comment by denfung** [comment]
@jpbrocca,

Can you advice?

Thanks,
Dennis

**Comment by jpbrocca** [comment]
@dirivero can you advice?

**Comment by mrutter** [comment]
@denfung: sorry, not sure I understood your question but I try to answer.
I have a similar problem and also I have a customized NavigationPage.

To set some properties of the NavigationPage while navigating, I simply do something like this:

**when navigating**
`_navigationService.NavigateAsync("NavigationPage?useTransparency=true/SomeOtherPage")`

**in my custom NavigationPage**
`public partial class NavigationPageBase : NavigationPage, INavigatingAware //, ...
{

	// ...

	public void OnNavigatingTo(INavigationParameters parameters)
	{
		if (parameters.TryGetValue("useTransparency", out bool useTransparency))
		{
			// Do something based on "useTransparency"
			// For example, in my case:
			GrialNavigationPage.SetIsBarTransparent(this, useTransparency);
		}
	}
	
	// ...

}
`
Hope this helps, otherwise forgive me for misunderstooding.

Kind Regards.
-m

**Comment by denfung** [comment]
@mrutter,

Thanks for your comment. 

Yes, that is what I am trying to achieve.
 Appreciate your help.

Thanks & best regards,
Dennis
