### ISSUE TITLE
How to change the DashboardCarouselPage icons in NavigationDashboards.json file?

### ISSUE THREAD

**Issue by narsi24** [UXDivers/Grial-UI-Kit-Support#599]
Hello,

We would like to use the "DashboardCarouselPage" to show contents using new icons and dynamic texts

### Description
With a freshly downloaded project, the Dashboard with Carousel showing the default data based on the NavigationDashboards.json file. We would like to change the existing icons in the NavigationDashboards JSON file

### Steps to Reproduce
Go to the Grial Kit Admin
Download a copy of the solution project 
Try to change the icon images in the  NavigationDashboards.json file (Dashboard with Carousel form)
Deploy into the Andriod device

### Basic Information
- Version with issue:
- Last known good version:
- IDE:  VS2019
- Platform Target Frameworks:
  - Android:  21

Could you please provide the resolution to update the icons in the JSON file and also dynamic texts in the DashboardCarouselPage

**Comment by jpbrocca** [comment]
Hello @narsi24,

If you want to change icons in design time data (JSON files in Grial), you will need to keep a few things in mind:

- Each icon will need to match the font being used, that means, that if you want to use an icon available in `grialiconsfill.ttf`, you will need to reference the right font family, otherwise, you won't see the icon properly. 
Please refer to this link for further details: http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons
- Each icon maps with a font glyph that should be available in the font. You can check [Grial font helpers](http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-font-helpers) to get each glyph value. That means if you want to use the right glyph in a JSON file you will need to copy the glyph value from the font helper (.cs file) and paste it in your JSON file. Check below picture for more details:

![image](https://user-images.githubusercontent.com/15996999/61662735-66747400-aca5-11e9-89c8-ad14d4a92145.png)

Let me know if you have more questions.

Best regards,
JP

**Comment by narsi24** [comment]
Thanks, JP for the response. Now I am able to update the icons in the JSON file using grialiconsfill.ttf, icons.

Cheers
NS
