### ISSUE TITLE
Grial Checkbox not working properly in Repeater

### ISSUE THREAD

**Issue by Nanouz** [UXDivers/Grial-UI-Kit-Support#608]
Hi

I want to put a checkbox in a repeater but the label text is not showing up.

```
        <grial:Repeater
            ItemsSource="{ Binding Listing }"
        >

            <grial:Repeater.ItemTemplate>
                <DataTemplate>
                    <grial:Checkbox>
                        <Label Text="{ Binding Name }"
                               TextColor="{ DynamicResource AccentColor }"/>
                    </grial:Checkbox>
                </DataTemplate>
            </grial:Repeater.ItemTemplate>

        </grial:Repeater>

        public ObservableRangeCollection<CategoryListItem> Listing
        {
            get => _listing;
            set => SetProperty(ref _listing, value);
        }

    public class CategoryListItem
    {
        public int Id { get; set; }
        public int Order { get; set; }

        public string Name { get; set; }
    }
```

**Comment by jpbrocca** [comment]
Hi @Nanouz,

Some questions to help you find the root of this issue:

1. What happens if you just leave the `<Label Text="{ Binding Name }" TextColor="{ DynamicResource AccentColor }"/>` inside the `DataTemplate`? 
   - Do you get anything rendered? If not, try just hardcoding some text inside the `<Label>` and see what happens.
2. Did you make sure you have enough width to allow the text to be displayed? 
   - You can use the `ItemSize` property from [repeater](http://docs.grialkit.com/repeater.html).

Let me know how it goes.

Regards,
JP

**Comment by Nanouz** [comment]
@jpbrocca The ItemSize property seems to be the problem. I did not know you need to set this. Do you also need so set a specific height? Now I get only a few rows.

**Comment by dirivero** [comment]
Sorry for not answering this before. I guess you've already made this work but in any case... yes, the `Repeater` requires you to define the `ItemSize`. That size indicates either the items height (when `Orientation="Vertical"`) or the items width (when `Orientation="Horizontal"`). 

The other dimension size is taken from the repeater itself considering the `Padding` and the `ScrollPadding` of course, so there's no need to define that. Here's there's more info:
http://docs.grialkit.com/repeater.html
