### ISSUE TITLE
Application Performance Issues after adding Grial

### ISSUE THREAD

**Issue by scorpio2000** [UXDivers/Grial-UI-Kit-Support#61]
Hello, 

I added Grial-UI-Kit to an existing application. The application is working great on android in debug mode in visual studio. However, as soon as I build in release mode or deploy it to playstore, the application becomes really slow and crashes repeatedly. I removed all the references to Grial to test and it starts working without any issues. The iOS works without any issue in all configurations in iOS. Are there any specific setting that we need to make for linking or otherwise when release android version? The application is completely unusable in it current state. Please advice

**Comment by jpbrocca** [comment]
Hi @scorpio2000, how are you?

Just a few questions:

- Are you using Grial 1.5 version ?
- Which Xamarin Forms version are you using ?
- Which Android version/s are you testing with ?

Thanks,
JP

**Comment by scorpio2000** [comment]
Hi JP,

Thanks for your reply.

The dll version of Grial is 1.5.0.12366
The version of Xamarin forms is 2.2.0.31
We tested with devices on Android 5.0 (Samsung Galaxy S5)

Thanks,
Pawan

**Comment by scorpio2000** [comment]
Hi JP,

We did some more testing with the Xamarin Profiler and it seems that Grial components are not getting disposed properly. We ran the Grial sample itself and it seems to have the same issue. We had planned a release of the beta version of our application on Monday but this issue has made the application completely unusable. I will really appreciate if you could look into this at your earliest convenience. I want to clarify again that we have tested by removing the Grial controls and it works perfectly okay. We created a separate page in the application using a regular list that is used to navigate to different pages. It works fine no matter how many times we navigate to any page and back. We implement the same functionality using Grial dashboard and it crashes after we have navigated few time (1 to 5 times). The navigation itself is really slow as compared to the page using non Grial components.

**Comment by jpbrocca** [comment]
Hi @scorpio2000,
Thanks for the details, we are already investigating to try to find the root of this issue.

Could it be possible that we had a chat on skype so you guys could show me more in detail? I think that will help us to move faster and find the issue and fix it.

Please, send me an email to jpbrocca@uxdivers.com so we can coordiante.

Thanks,
JP

**Comment by jpbrocca** [comment]
Hi @scorpio2000, how are you ?
Hopefully, it seems we found the problem and the solution :)

I am going to share the info here for other customers who could be facing the same issue.
Can you close this issue whenever you had a moment?

Also if you had more comments to share with other guys that could be experiencing the same issues that would be much appreciated!
Thank you!

---

So about this issue: 
This is not related to Grial. This problem happens due to a bug introduced by xamarin forms on 2.2.

# When using a MainActivity that inherits from FormsAppCompatActivity NavigationPages are not released and leak memory.  
This behaviour is not observed when using a MainActivity that inherits from FormsApplicationActivity:
https://bugzilla.xamarin.com/show_bug.cgi?id=40955

Since Grial 1.5 added support for AppCompatV7 this issue is present, but, the problem is that this is not detectable under development, meaning that when you debug your app this will be not noticeable. It only becomes evident when you switch to Release!

This is fixed by Xamarin on:
**2.3.1-pre1 on nuget**

**Comment by scorpio2000** [comment]
Juan, thank you so much for working through the weekend to help us resolve the issue. I can confirm that the issue is resolved with the pre-release package. We seem to be having some issues with that package with android version 4 but that has nothing to do with Grial. Our application is running really fast after updating the package. Thanks again for your help.

**Comment by james-lavery** [comment]
Looking at this issue, can you confirm whether under:
Grial 2.0.60
Xamarin.Forms 2.3.4.270
this issue is fixed?

**Comment by ShamineDsouza** [comment]
i am facing similar issue .  Xamarin forms 4.4
Grial 3.0

**Comment by dirivero** [comment]
Could it be related to this? https://github.com/UXDivers/Grial-UI-Kit-Support/issues/786#issuecomment-819526003
