### ISSUE TITLE
license issues and hello@grialkit.com support email is broken

### ISSUE THREAD

**Issue by jcbdev** [UXDivers/Grial-UI-Kit-Support#610]
I have license issues but the support email in the admin section does not work.  I've tried emailing from two different source emails and it consistently gets bounced back.

**Comment by LeoHere** [comment]
@jcbdev sorry for the inconvenience. Recently we changed the email because we were having issues with that address. 

Please describe here what kind of License issue you are experiencing or email us to grialkit at uxdivers.com. 

Most common license issues and the solution are described [here](https://docs.grialkit.com/troubleshooting.html#troubleshooting-license-issues).

**Comment by jcbdev** [comment]
i've sent email. Thanks.

**Comment by LeoHere** [comment]
@jcbdev I didn't see it passing through... are you sure you sent it to the correct email address?

You can double-check if the email address is correct by going to the Help page of the Grial Admin (we fixed it, thanks for letting us know). 

![image](https://user-images.githubusercontent.com/16000584/62736357-8d4fdb80-ba03-11e9-94c0-c8e2293d6fa8.png)
