### ISSUE TITLE
ListView scroll issue in TabControl 

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Grial-UI-Kit-Support#619]
ListView unable to scroll, load more or refresh when inside a TabControl in an android device.

Description
Scroll action not working on Xamarin Forms ListView. 

Steps to Reproduce
Populate a ListView inside a TabControl in any of its TabItems.

Expected Behavior
Allow List Scroll, Load more, Refresh, Selection and other list actions.

Actual Behavior
Unable to scroll ListView. Gets a frozen list. Load More & Refresh actions also not working.

Basic Information

- Version with issue:  UXDivers.Artina.Controls.Tab - 2.7.7
- IDE: Visual Studio Community for Mac 8.2.5
- Platform Target Frameworks: 
- Xamarin.iOS Version: 12.14.0.114
- Xamarin.Android Version: 9.4.1.0
- Xamarin Forms Version : 4.1.0.673156
- Affected Devices: All Android Devices

Please look into the issue @jpbrocca

**Comment by jpbrocca** [comment]
HI @khadeeja-alif, how are you?

It seems from your email sent earlier today that this issue is not caused by Grial, but for this issue in Xamarin Forms:
[[Bug] ListView scroll not working when is inside a ScrollView #7329](https://github.com/xamarin/Xamarin.Forms/issues/7329)

I am leaving the info here in case that could help someone else facing this issue.

Regards and thanks,
JP

**Comment by muhaym** [comment]
Yes the issue is because of https://github.com/xamarin/Xamarin.Forms/issues/7329
