### ISSUE TITLE
iOS 13, No PlaceholderColor in Entry, SearchBar 

### ISSUE THREAD

**Issue by stivenbr** [UXDivers/Grial-UI-Kit-Support#630]
Hi Grial !

### Description
1. No color Placeholder in Entry and SearchBar 

### Screenshots
![alt text](https://i.ibb.co/LkHQ3Bp/bug-placeholder.png)

### Basic Information
- Version with issue: Grial 3 pro
- Last known good version: -
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  11 - 13
- Nuget Packages: **`UXDivers.Grial 3.0.52-RC`**

### Thanks !

**Comment by dirivero** [comment]
Hi there!

This is already reported in the Xamarin.Forms repo, please check the status here:
https://github.com/xamarin/Xamarin.Forms/issues/7695

**Comment by attrib75** [comment]
@dirivero  Is this also why the searchbar FieldBackGroundColor no longer works?

**Comment by dirivero** [comment]
I see that it works in iOS 12 and 13. What version of Xamarin.Forms are you using?

**Comment by attrib75** [comment]
For me it stopped working in iOS 13.  I'm using xamarin forms 4.2.0.848062, grial 2.7.1

thanks

**Comment by dirivero** [comment]
Ok, I was trying with grial 3. That should be the difference. I will check.

Regarding the original problem of the placeholder color here are a couple of workarounds:
* set the color in the `OnAppearing` method of the page
* extend Giral iOS renderer with the code below and declare it as the renderer for searchbars 

```
public class SearchBarPlaceholderColorFixRenderer : SearchBarRenderer
{
    public override void LayoutSubviews()
    {
        base.LayoutSubviews();

        if (Element != null)
        {
            var color = Element.PlaceholderColor;
            Element.PlaceholderColor = Color.Default;
            Element.PlaceholderColor = color;
        }
    }
}
``` 

```
[assembly: ExportRenderer(typeof(SearchBar), typeof(SearchBarPlaceholderColorFixRenderer))]
```

The problem comes from apple:
https://stackoverflow.com/questions/57820342/ios-13-set-uisearchtextfield-placeholder-color

**Comment by dirivero** [comment]
We've included this workaround as part of the new Grial version `3.0.54`.
I will close the issue now.

**Comment by attrib75** [comment]
thanks
