### ISSUE TITLE
Toolbox for Grial controls

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#654]
Hi,

How can I show the toolbox of grial kit controls to gdrag and drop on my xaml file please?

Thanks,

**Comment by dirivero** [comment]
Hi, 

Since XAML files are not editable in a wysiwyg manner but as text files previewed in a device/simulator with Xamarin's Hot Reloader or Gorilla Player for instance, we don't provide a specific toolbox for our controls that just outputs a default xaml tag with default values.

You can find multiple examples of real usage of our controls in Grial pages, and what's more important, they are in the context of a template that looks already looks good so I recommend you to base your code in them as opposed to write it completely from scratch.

You can also get XAML code examples from our docs: http://docs.grialkit.com/

Hope this helps.

**Comment by dalton5** [comment]
Ok thanks for your response. 

And I have just purchased grialkit. What is the difference between hot reloader and gorilla player?

Gorilla works better with grialkit?

Thanks

**Comment by dirivero** [comment]
Both work fine with Grial. Gorilla Player has a great integration since we do both but the 2 tools are important. I would say it depends on the sage of the project you are in and the task at hand which one to use.

By using Gorilla you can take advantage of Grial's json sample data that is super easy to manipulate in order to populate your Xaml bindings with your own domain data and have a clearer picture of how your pages will look. Also, Gorilla lets you preview in multiple devices and simulators at once which greatly simplifies the task of supporting multiple screen sizes, platforms and orientations.

On the other hand, the hot reloader actually runs your app with your logic instead of previewing it. That is great once you have the app connected to a backend displaying real data. Also, have in mind that it supports one device/simulator at a time since the VS debugger has to be attached for it to work.

I would recommend using Gorilla with Grial to craft all your screens initially and adjust them to different devices. Once you have your app logic ready, if you need to make some tweaks/fixes I would use the hot reloader since the sample data would not be in-sync by that time. If you need to add a few more screens I would use Gorilla once again.

Hope this helps.
