### ISSUE TITLE
CurvedMask custom

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#668]
Hi,

I try to accomplish this on the top of the screen:

![image](https://user-images.githubusercontent.com/8339768/71673676-b2116a80-2d79-11ea-92eb-ce50747430e0.png)

I try to use the svg by inspiring with CurvedMask.

I tried this: 

> <svg xmlns="http://www.w3.org/2000/svg" width="375" height="41">

    <path fill="#FFF" fill-rule="evenodd" d="m57.5,78.445313c0,-6.520548 5.479452,-12 12,-12l262,0c6.520548,0 12,5.479452 12,12l0,114c0,6.520548 -5.479452,12 -12,12l-262,0c-6.520548,0 -12,-5.479452 -12,-12l0,-114z" />
</svg>

But I can't get it to work.

I have this triangle at the bottom left. Can you help?

Thanks,

![image](https://user-images.githubusercontent.com/8339768/71674054-935fa380-2d7a-11ea-9aad-a7b3a1b01c45.png)

**Comment by jpbrocca** [comment]
Hi @dalton5,
I guess you replaced the content inside `curved_mask.svg` file.
Most probably you are getting that triangle because the original height of `curved_mask.svg` is still the same. You should put the right height. Additionally you will need to position your image at the right place (you will need to make sure you are using `VerticalOptions` properly, and also you will need to make sure you are putting this image at the right Grid row) .

Hope that helps. 

Regards 
JP
