### ISSUE TITLE
Add better support for tablets

### ISSUE THREAD

**Issue by Laumania** [UXDivers/Grial-UI-Kit-Support#7]

**Comment by dirivero** [comment]
I'm going to close this issue because the current support for tablets in Grial is much better than it was when this was posted :)

The templates are optimized for tablets and we also provide responsive helpers to give more flexibility to our customers to adjust their screens to different devices:
http://docs.grialkit.com/responsive-helpers.html

As always, thanks @Laumania ! :)

**Comment by Laumania** [comment]
@dirivero Thanks and yes, tablet support are great now so no complains there :)

👍
