### ISSUE TITLE
XLabsForms Support

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#73]
Just wondering if you've successfully integrated this with Xamarin Forms Labs.  I can get Grial to work by itself, but when I add XLabs, and change the MainActivity to inherit from XFormsApplicationDroid, I get this:

https://forums.xamarin.com/discussion/74242/null-reference-exception-android-platform-updateactionbarbackgroundcolor-on-app-start#latest

**Comment by jpbrocca** [comment]
Hi @attrib75,

No, we didn't ourselves, but as far as I know some of our customers use both.

We will review this for Grial 2.0.

Thanks,
JP

**Comment by attrib75** [comment]
ok, any idea on how this is accomplished? thanks

**Comment by jpbrocca** [comment]
Hi,
it seems that XLabs didn't add support for AppCompat yet, and that is why it should be failing -since Gria 1.5l uses AppCompat-.
Here seems to be some workaround from XLabs, you should check these:

https://github.com/XLabs/Xamarin-Forms-Labs/issues/998
https://github.com/XLabs/Xamarin-Forms-Labs/issues/1210

Regards,
JP

**Comment by dirivero** [comment]
Closing this old issue. XLabs is not maintained anymore.
