### ISSUE TITLE
DataGrid cell dynamic background color - CellTemplateBindingContextPath

### ISSUE THREAD

**Issue by SergeyChtcherbakov** [UXDivers/Grial-UI-Kit-Support#757]
I'm trying to set a background color on DataGridColumn dynamically if API returned specific hex color.
Here is the code example:

```
foreach (var column in uniqueColumns)
                    {
                        var col = new DataGridColumn
                        {
                            HeaderText = column,
                            BindingPath = $"Prop{uniqueColumns.IndexOf(column) + 1}",
                            CellTextAlignment = TextAlignment.Center,
                            HeaderTextAlignment = TextAlignment.Center,
                            HeaderTextColor = Color.White,
                            ColumnWidth = 100,
                            CellFontSize = 11,
                            HeaderFontSize = 12
                        };
                        col.SetBinding(DataGridColumn.CellBackgroundColorProperty, $"{col.BindingPath}Colour", BindingMode.Default, new HexToColorConverter());
                        
                        sampleGrid.ColumnDefinitions.Add(col);
 }
```

That doesn't work. 
I found that there is a new property 
`CellTemplateBindingContextPath`
which can help reuse the column definitions with different data. However, I was not been able to find an example.

Any help appreciated.

I also noticed that the DataGrid in iOS doesn't let me scroll the page, it is trying to scroll the DataGrid, even though I set the HeightRequest to be the actual table height.

Thanks.

**Comment by dirivero** [comment]
The column definition doesn't have the binding context of each cell, so binding the color on the cells to the column won't work.

To do something like that you will need to define a specific cell template like this:

```
    <grial:DataGridColumn HeaderText="column header">
        <grial:DataGridColumn.CellTemplate>
            <DataTemplate>
                <Grid BackgroundColor="{ Binding Prop1Colour, Converter={StaticResource HexToColorConverter} }">
                    <Label Text="{ Binding Prop1 }"/>
                </Grid>
            </DataTemplate>
        </grial:DataGridColumn.CellTemplate>
    </grial:DataGridColumn>
```
I understand you want to add the columns dynamically so that needs to be written in c#. It can be done like this:

```
grid.ColumnDefinitions.Add(
      new DataGridColumn
      {
          HeaderText = "column header",
          CellTemplate = new DataTemplate(() =>
              new Grid {
                  Children =
                  {
                      new Label().Bind(Label.TextProperty, "Prop1")
                  }
              }.Bind(Grid.BackgroundColorProperty, "Prop1Colour", new HexToColorConverter())
          )
      });
``` 

You can generalize that into your foreach loop to get the expected result.

Note that I used the markup extensions to simplify the code, basically I used the `Bind`. To use those you need to set this flag before initializing forms `Forms.SetFlags("Markup_Experimental")`. You can read more about that here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/creating
