### ISSUE TITLE
Urgent *** In Production App crashing giving  Grial Issue

### ISSUE THREAD

**Issue by ShamineDsouza** [UXDivers/Grial-UI-Kit-Support#768]
Dear team ,

***Urgent help .

I have recently published my app in production , but the app seems to be crashing .
Following is the error , I am facing with states grial license.

My grial license is currently in development mode .    Can this be the reason for the error. 
If Yes , If I change it to production mode , what are the things I will not be able to change in the admin console . That I could change in admin console when it was in  development  mode .
Please help.

![IMG-20201109-WA0011](https://user-images.githubusercontent.com/25946929/98633048-b3b0a500-2331-11eb-8b6a-b2beed394dc3.jpg)

**Comment by dirivero** [comment]
Hi @ShamineDsouza, 

You should never publish your app with a development license since it will expire in <= 30 days blocking the users that have it installed. Unless of course you have a controlled testing environment where you can "force" people to update.

Please refer here for more information: 
http://docs.grialkit.com/grial-web-admin.html#grial-web-admin-grial-license-setup-license-modes

Related to the issue itself, how does your Android release config looks like? Is it possible you have the "link all" option? Can you reproduce it locally?
