### ISSUE TITLE
Just purchase and unable to make the sample app run

### ISSUE THREAD

**Issue by silkcreativeworks** [UXDivers/Grial-UI-Kit-Support#78]
I have just purchased Grial UI kit. I am able to compile the original solution (no changes made) that comes with Grial using Visual Studio Enterprise 2015 and setting Grial.Droid as the startup project. 

After the default emulator loads (5" KitKat (4.4) - Android 4.4 - API 19), I click on the Grial app and the Splash screen is displayed for few seconds and then it return to the phone home page. I tried clicking a few times and the same thing happens.

Has anyone experienced this and knows what's happening?

Thanks.

**Comment by jpbrocca** [comment]
Hi @silkcreativeworks,

Are you trying to debug the sample app or did you compile in release mode?
If it is the second have a look at this:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/61

If it is the first, then we will need more info since this has not been reported.
Are you trying with VS android emulator only? 
Do you have any other simulator like genymotion or the ones provided by xamarin so you could also test on them?

You could also try to update to latest xamarin forms version and check if you still experience this on your emulator.
Best,
JP

**Comment by AccountsIt** [comment]
Sorry to say that again, but your tutorials suck. 
I have the same problem like the other user. I thought I purchase your stuff, and AT LEAST your own demo version is plug and play. 
But now I just opened your project, and received 27 errors and 8 warnings. 
Even free stuff is better organised, build up with tutorials and how-to wikis.
Why not creating a simple "Step by step guide on how to get the demo version to run?" 
If you want to have a real business, get your must-haves done!

**Comment by jpbrocca** [comment]
Hi @AccountsIt,
sorry to hear that.
We are working hard to improve our documentation and to make easier to setup a Grial project.

I appreciate your suggestion and this is something will be improved in the near future.
Meanwhile, If you could provide more info about the errors you get I will help you with your issues.

Best,
JP

**Comment by AccountsIt** [comment]
Hi @jpbrocca thanks for answering.
I thought you are on the market since 2015? And still you could not set up a propper introduction? 
This would only take one hour? Maybe two if you wanna add pictures in the mix. But still - There is no excuse for not having a proper introduction, readme.txt or whatever. Just put it from the nice-to-have into the must-have list asap.

I have the same issues as in this thread mentioned:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/66


Here is a screenshot:
https://drive.google.com/open?id=0B4VtoSoDb9_tRHVNQW9GbTBISXc

**Comment by AccountsIt** [comment]
What I did so far:
Downloaded Xamarin Community Studio on Mac.
And opened your "grialkit1.5.2/samples/grial/droid/grial.droid.csproj" project.

**Comment by jpbrocca** [comment]
Hi @AccountsIt,
It seems you are on Android (which is problematic on Xamarin specially when the packages are updated by Xamarin Studio/Visual Studio).

Did you update packages first? 
If not, please try to update and keep in mind the following recommendation from Xamarin:
"When upgrading Xamarin.Forms, take care not to simply "update all" as that will update the Xamarin.Android.Support packages to an incompatible version."
https://developer.xamarin.com/guides/xamarin-forms/troubleshooting/

After that, try with a clean/rebuild and finally run.
You could also try deleting bin & obj folders.

You could also try with the solutions from here:
https://forums.xamarin.com/discussion/60431/appcompat-no-resource-found-that-matches-the-given-name-theme-appcompat-light

Let me know how it goes.

Best,
JP

**Comment by AccountsIt** [comment]
Can you please create a full documentation, on a blank pc, how to set up your project?
Step 1: Install version X.X from Visual Studio. 
Step 2: Download Grial
Step 3: Install Nuget Package XY in version x.x
Step 4: Delete X and Y
Step 5: Update SDK to x.x
...
In my opinion you have to create at least one single working documentation, in which everything is working!

**Comment by pixou94** [comment]
So far this is what worked for me :
Download grial
Open in VS
Uninstall the nuget package Xamarin.Forms in the Grial ( Portable) project
Reinstall the same nuget package in the same version. ( <--- VERY IMPORTANT)
Compile
Enjoy :)

**Comment by garymedina** [comment]
Hey I am trying to run Grail V.2 on my Mac and getting Packages not found also. It appears for me that the Nuget Repo is unreachable/ Not found and the Mac can't restore the Grail packages. I did try this on my PC and it worked but the Mac can not communicate with the Nuget Repo with the same exact credentials.

So did you get it to work? and how?

**Comment by LeoHere** [comment]
@garymedina there is no special consideration for the Mac. It should work as in Windows. Are you using XS or VS for Mac?

Please double check that you are using the correct URL when registering Grial Package Source. Also, you can test that the Nuget server is reachable by pasting its URL in your Browser. You will be prompt for credentials and once you successfully enter them an XML will be displayed.

**Comment by LeoHere** [comment]
Closing the issue to keep things tight. Feel free to reopen it if you need so.
