### ISSUE TITLE
Provide documentation for the MAUI Map control.

### ISSUE THREAD

**Issue by hitchhiker** [UXDivers/Grial-UI-Kit-Support#836]
The December update mentions the GrialMap control has been released for MAUI:
https://grialkit.com/blog/grial-ui-kit-4-for-net-maui-december-update

.. but no documentation seems to be available for it, nor does NuGet seem to include it in the main package (and no pre-release versions) it's not included in the pages/controls on the admin portal either. 

I purchased the Pro kit specifically for this control, is there something I'm missing? Thanks in advance.

**Comment by dirivero** [comment]
Hi! 

The Map Flow (which are the screens showcasing the GrialMap) will be published tomorrow. The API of the control is the same as it was in Xamarin. We didn't include those pages because the XAML required some tweaks but not the part from the map, so, if you want to use the maps today you can follow that documentation or download the Xamarin Map Flow and grab the map code from there.

https://docs.grialkit.com/controls/grial_map

**Comment by hitchhiker** [comment]
Appreciate you getting back to me so quickly... will wait till tomorrow :)

_I'm enjoying the Grial experience so far, it's going to save us countless hours. Thank you!_
