### ISSUE TITLE
New version of the library

### ISSUE THREAD

**Issue by homerokzam** [UXDivers/Grial-UI-Kit-Support#94]
Is there any plans to launch an update of the library?

Thanks,
Homero

**Comment by jpbrocca** [comment]
Hi @homerokzam, how are you?
Yes, we will be releasing Grial 2.0 in a few Weeks more.

Best regards,
JP

**Comment by homerokzam** [comment]
Due to the quality of the product of you, I hope anxious for news.

Thanks,
Homero

**Comment by jpbrocca** [comment]
Thanks Homero :)
Stay tuned!

Regards,
JP

**Comment by weilitao** [comment]
Hi, how about the new version? any release plan?

**Comment by jpbrocca** [comment]
Hi @weilitao, thanks for your interest on Grial 2.0.

Currently we are experiencing some dalys mostly because of instability of latest Xamarin updates.
We are waiting for them to release an update that would fix some of the bugs they recently introduced with latest versions.

We will announce the release as soon as this happens.

Best,
JP
